### ISSUE TITLE
[error C2668] 'std::uncaught_exception'

### ISSUE THREAD

**Issue by JonLiu1993** [ClickHouse/clickhouse-cpp#100]
Hi Clickhouse Team:
When i update clickhouse-cpp to version 1.5.0. I build failed due to:
````
error C2668: 'signbit': ambiguous call to overloaded function
````
https://github.com/ClickHouse/clickhouse-cpp/blob/1415b5936a2ac2f084850b09057e05fb5798b2f1/clickhouse/columns/decimal.cpp#L32

I have a temporary workround, I want to know if it is feasible, or do you have a better solution?
````
diff --git a/clickhouse/columns/decimal.cpp b/clickhouse/columns/decimal.cpp
index 7334bb1..41d43b6 100644
--- a/clickhouse/columns/decimal.cpp
+++ b/clickhouse/columns/decimal.cpp
@@ -27,7 +27,7 @@ inline bool mulOverflow(const Int128 & l, const T & r, Int128 * result)
 
 #else
 template <typename T>
-inline bool getSignBit(const T & v)
+inline bool getSignBit(const T & (long double v))
 {
     return std::signbit(v);
 }

````
Related pr [#18330
](https://github.com/microsoft/vcpkg/pull/18330)

**Comment by inaryart** [comment]
hi @Enmk , I also encountered this problem (windows vs2019), is there any good solution

**Comment by Enmk** [comment]
Should be now fixed by https://github.com/ClickHouse/clickhouse-cpp/pull/128
Also, we now have full support of Windows for both msvc (https://github.com/ClickHouse/clickhouse-cpp/pull/131) and mingw (https://github.com/ClickHouse/clickhouse-cpp/pull/137) builds
