### ISSUE TITLE
A friend from Facebook noticed that BUCK does not work anymore.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-cpp#106]

**Comment by alexey-milovidov** [comment]
More context:

Looks like open-source version of Buck is almost unsupported by Facebook and better to use Bazel instead.

**Comment by Enmk** [comment]
There are no plans to support exotic build systems yet, but any contributions are welcome.

**Comment by alexey-milovidov** [comment]
There should not be any garbage in the source code repository. I removed BUCK.
