### ISSUE TITLE
AppendAsColumn doesn't work with Array of Decimals

### ISSUE THREAD

**Issue by astiunov** [ClickHouse/clickhouse-cpp#11]
There is a minimal example: https://pastebin.com/RJmKpZ33, which works if you replace ColumnDecimal with ColumnDate or ColumnInt64 for a example.

The second assert fails, because AppendAsColumn calls [this method](https://github.com/ClickHouse/clickhouse-cpp/blob/7cb0a699a59f421f694c58e1217c8343ae2876f1/clickhouse/columns/numeric.cpp#L41). ColumnDecimal isn't inherited from ColumnVector, so the check there fails.

**Comment by Enmk** [comment]
Fixed in #161, see Unit test here:
https://github.com/ClickHouse/clickhouse-cpp/blob/master/ut/columns_ut.cpp#L956
