### ISSUE TITLE
static lib can not link other libs 

### ISSUE THREAD

**Issue by tiger-bo** [ClickHouse/clickhouse-cpp#121]
[xubo@ldw0 clickhouse]$ ar tv libclickhouse-cpp-lib-static.a
rw-rw-r-- 1002/1002 557640 Dec  2 16:37 2021 compressed.cpp.o
rw-rw-r-- 1002/1002 302328 Dec  2 16:37 2021 input.cpp.o
rw-rw-r-- 1002/1002 353352 Dec  2 16:37 2021 output.cpp.o
rw-rw-r-- 1002/1002   1352 Dec  2 16:37 2021 platform.cpp.o
rw-rw-r-- 1002/1002 885760 Dec  2 16:37 2021 socket.cpp.o
rw-rw-r-- 1002/1002 367632 Dec  2 16:37 2021 wire_format.cpp.o
rw-rw-r-- 1002/1002 1108672 Dec  2 16:37 2021 array.cpp.o
rw-rw-r-- 1002/1002 1784104 Dec  2 16:37 2021 date.cpp.o
rw-rw-r-- 1002/1002 1169608 Dec  2 16:37 2021 decimal.cpp.o
rw-rw-r-- 1002/1002 1529896 Dec  2 16:37 2021 enum.cpp.o
rw-rw-r-- 1002/1002 4277000 Dec  2 16:37 2021 factory.cpp.o
rw-rw-r-- 1002/1002 836272 Dec  2 16:37 2021 ip4.cpp.o
rw-rw-r-- 1002/1002 858592 Dec  2 16:37 2021 ip6.cpp.o
rw-rw-r-- 1002/1002 2108496 Dec  2 16:37 2021 lowcardinality.cpp.o
rw-rw-r-- 1002/1002 919880 Dec  2 16:37 2021 nullable.cpp.o
rw-rw-r-- 1002/1002 5784904 Dec  2 16:37 2021 numeric.cpp.o
rw-rw-r-- 1002/1002 1317040 Dec  2 16:38 2021 string.cpp.o
rw-rw-r-- 1002/1002 693320 Dec  2 16:38 2021 tuple.cpp.o
rw-rw-r-- 1002/1002 820888 Dec  2 16:38 2021 uuid.cpp.o
rw-rw-r-- 1002/1002 475848 Dec  2 16:38 2021 itemview.cpp.o
rw-rw-r-- 1002/1002 1616272 Dec  2 16:38 2021 type_parser.cpp.o
rw-rw-r-- 1002/1002 1836464 Dec  2 16:38 2021 types.cpp.o
rw-rw-r-- 1002/1002 872624 Dec  2 16:38 2021 block.cpp.o
rw-rw-r-- 1002/1002 3562208 Dec  2 16:38 2021 client.cpp.o
rw-rw-r-- 1002/1002 435856 Dec  2 16:38 2021 query.cpp.o
[xubo@ldw0 clickhouse]$

the source code 
```
ADD_LIBRARY (clickhouse-cpp-lib-static STATIC ${clickhouse-cpp-lib-src} )
TARGET_LINK_LIBRARIES (clickhouse-cpp-lib-static
    absl-lib
    cityhash-lib
    lz4-lib
)
```

**Comment by Enmk** [comment]
Hi @tiger-bo, could you please specify the error message or some other context that could help fixing this?

**Comment by Ziemien** [comment]
I think what he means is that the `TARGET_LINK_LIBRARIES` does not actually add listed dependencies to the `clickhouse-cpp-lib-static` so then when one uses only the static lib provided the linker is can't find symbols i.e `ld.lld: error: undefined symbol: CityHash64(char const*, unsigned long)`

I am seeing the same problem as neither of the deps like lz4 or cityhash are actually part of the produced archive.

**Comment by Ziemien** [comment]
this seems to be solved by using cmake flag `DBUILD_SHARED_LIBS=ON`

**Comment by pkoosha** [comment]
I am requesting to open this issue and propose an actual solution for static libraries.
