### ISSUE TITLE
About ColumnDateTime

### ISSUE THREAD

**Issue by hgisxian** [ClickHouse/clickhouse-cpp#123]
Hello
This is my example：
[root@localhost bak]# time cat map_s11_map_2021091411_0000714279 | clickhouse-client --host=127.0.0.1 --port=9000 --user=default --database=default --format_csv_delimiter='|'  --query="INSERT INTO epc_map_s11_date FORMAT CSV" 1>err_epc_map_s11_.txt 2>&1

real    0m0.613s
user    0m0.502s
sys     0m0.228s

It only takes 0.613s for me to use clickhouse-client to store one million data, but when I use clickhouse-cpp to assign each data, due to the field type ColumnDateTime,I need a lot of time to convert the string to time_t type (it takes at least 3S to produce this data). This is too inefficient. Can I handle ColumnDateTime type like clickhouse-client？
Please give me some advice, thank you.

**Comment by Enmk** [comment]
Hi @hgisxian ! Sorry for a late reply.

Now sure what do you actually mean, but right now `ColumnDateTime` stores/takes/returns `time_t`. So I am not quite sure where exactly you do type conversion. Could you share some code examples?

**Comment by Enmk** [comment]
Closed due to inactivity
