### ISSUE TITLE
error: fail to ping server

### ISSUE THREAD

**Issue by CedrusZhao** [ClickHouse/clickhouse-cpp#124]
when I use client.Ping() , I get the problem:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  fail to ping server
```

**Comment by Enmk** [comment]
Hi @CedrusZhao! Could you please provide a minimal viable code example that reproduces an error?

**Comment by CedrusZhao** [comment]
sorry， I have miss the code.
