### ISSUE TITLE
'Failed to connect' exception using MSVC

### ISSUE THREAD

**Issue by xiangyue1993** [ClickHouse/clickhouse-cpp#127]
Hello,

I was using MSVC to build clickhousecpp (version 2.0.0) on Windows, and the static library was generated successfully. However, an exception of ```failed to connect``` occurred when I run the **simple-test** project. There is a clickhouse server running on my localhost, exposing the 9000 port. I test the connection with python ```clickhouse_driver``` and everything is ok.

By the way, I encountered a problem with ```signbit: ambiguous call to overloaded function``` when I was building the clickhousecpp library. The problem was solved according to [#100](https://github.com/ClickHouse/clickhouse-cpp/issues/100), and I don't know whether it is an official solution.

Is there any idea of this issue?

Thanks

**Comment by xiangyue1993** [comment]
I found the exception throw when creating the socket connection, and I cannot figure out what cause the issue since I'm not familiar with ```socket programming```. 

However, there was an older version of ```clickhousecpp``` (version of 3 years ago) on my PC, then I rebuilt the library, and it works well.

**Comment by xinstein** [comment]
How did you get msvc to compile clickhouse-cpp correctly?

**Comment by filimonov** [comment]
Depends on https://github.com/ClickHouse/clickhouse-cpp/issues/130
