### ISSUE TITLE
fail to connect to xxx when initializing Client object

### ISSUE THREAD

**Issue by ChunyunShen** [ClickHouse/clickhouse-cpp#133]
Hi, 
I want to use clickhouse-cpp to request remote server as I think this way is more efficient than HTTP request.
The remote server has installed clickhouse server and can work with HTTP request. 
However, when initializing a Client object, I got the following errors:

"terminate called after throwing an instance of 'std::runtime_error'
  what():  fail to connect to xxx.xxx.xxx.xxx
Aborted"

The codes for initialization are as follows:

`ClientOptions clicnt_options(ClientOptions()
                            .SetHost("xxx.xxx.xxx.xxx")
                            .SetPort(xxxx)
                            .SetPassword("******")
                            .SetPingBeforeQuery(true)
                            .SetCompressionMethod(CompressionMethod::LZ4));
Client clickhouse_client_(clicnt_options);`

**Comment by DanielKui** [comment]
I also meet this issue, How do you solve it?
