### ISSUE TITLE
How to set timeout config

### ISSUE THREAD

**Issue by ChunyunShen** [ClickHouse/clickhouse-cpp#141]
When I establish a clickhouse client to send requests to clickhouse server, I expect to set a maximum time for each request. When timeout occurs, client should stop waiting for server. However, I find in the class Client this mechanism is not supported. 
Are there any other ways to achieve this goal?

**Comment by filimonov** [comment]
Not supported now. Feel free to add/send PR.

See https://stackoverflow.com/a/2939145

**Comment by Enmk** [comment]
@ChunyunShen you can try using `Client::SelectCancelable` together with in-query `SETTING` clause. But right now there are no tests that properly verify that.

**Comment by King-Authur** [comment]
In the working environment, we encountered the situation that the clickhouse machine hangs up several times. At this time, the server can receive the client's request, but will not respond, which will cause the client to be stuck in the recv() link, which will affect the subsequent data. write.
Adding the timeout config and cooperating with the logic of switching the write replica when the write fails can avoid the above problems.

**Comment by rr0gi** [comment]
fixed in https://github.com/ClickHouse/clickhouse-cpp/pull/205 ?
