### ISSUE TITLE
Consider incorporating exceptions into type system

### ISSUE THREAD

**Issue by itrofimow** [ClickHouse/clickhouse-cpp#145]
As for now there are 62 places where `std::runtime_error` is thrown and 9 places where `std::system_error` is thrown,
and this makes it really hard to distinguish different kinds of errors programmatically.

Would be great if you could introduce something like `ParsingError`, `NetworkError` etc.

**Comment by Enmk** [comment]
Hi @itrofimow, sure, that'll be great! You are more than welcome to propose a PR.

**Comment by itrofimow** [comment]
@Enmk I'm planning on that)
Can you give me a lead on hierarchy/names you find desirable?

On a side note - i'm a bit concerned about this being technically a breaking change

**Comment by Enmk** [comment]
Well, never thought about it before, there are multiple groups of errors:
- protocol errors:
  - checksum failure
  - partial data
  - io errors
  - unimplemented packet type
  - failed to serialize or deserialize column
  - exception from server
- LZ4 errors
- SSL errors
- unimplemented Column Type

**Comment by Enmk** [comment]
So I propose something like this:
```mermaid
graph BT
    Exception --> e["std:::exception"]
    ValidationError --> Exception
    UnimplementedError --> Exception
    ThirdPartyError --> Exception
    OpenSSLError --> ThirdPartyError
    LZ4Error --> ThirdPartyError
    InternalValidationError --> Exception
```

**Comment by itrofimow** [comment]
Thank you for an elaborate answer!
This hierarchy looks good to me, so i'll try to implement exactly what you proposed
