### ISSUE TITLE
Not able to insert serialized protobuf data

### ISSUE THREAD

**Issue by rtkaratekid** [ClickHouse/clickhouse-cpp#154]
I'm having trouble inserting protobuf data into clickhouse using this cpp library.
When I use the cli client, it works fine
```
cat df_obj.bin | clickhouse-client --query "INSERT INTO dragonfly FORMAT Protobuf SETTINGS format_schema='schemafile:Dragonfly'"
```
But if I try to embed the command directly into the query e.g.
```
clickhouse-client --query "INSERT INTO dragonfly VALUES ($(cat df_obj.bin)) FORMAT Protobuf SETTINGS format_schema='schemafile:Dragonfly'"
```
Or if I try to build this out with the cpp client, something like this (which executes the same command)
```cpp
    std::stringstream cmd;
    cmd << "INSERT INTO " << this->db_name << " VALUES ";

    cmd << "(" << protobuf_obj << ") ";

    cmd << "FORMAT Protobuf SETTINGS format_schema='schemafile:Dragonfly'";
    client.Execute(cmd.str());
```

The error ends up being
```
terminate called after throwing an instance of 'clickhouse::ServerException'
  what():  DB::Exception: Cannot parse expression of type UInt32 here: �
```
This error makes me think that clickhouse is trying to parse a UInt32 from data that can't be coerced into it, but the object is a single protobuf object and I know my schema and everything lines up because the first cli command I listed above does work.

I'm happy to provide my db and/or protobuf schema if that would help, but I think this may be a misunderstanding on my part of how clickhouse expects insert statements to work and I have not been able to find helpful documentation for using the cpp client in this way.

Edit: I did go back to make sure that the data I'm trying to insert via the cpp client and the data I _successfully_ inserted via the cli were the same. They are the same, so I know it's not an issue with my data formatting.

**Comment by Enmk** [comment]
Please see the [tests](https://github.com/ClickHouse/clickhouse-cpp/tree/master/ut) and [examples](https://github.com/ClickHouse/clickhouse-cpp/tree/master/tests/simple) for usage reference.

Basically, `clickhouse-client` has a rich support of input/output format, but for `clickhouse-cpp` you are expected to provide raw C++ values, like `int`'s, `string`'s, etc.

**Comment by rtkaratekid** [comment]
Thanks for the response, I have looked through both tests and examples to find were binary data formats were being inserted without the `Block` type. You're basically saying that data is intended to be inserted via `Block`, and everything else is considered unsupported?

This may be true, but it also doesn't explain why the insert query fails with the same error, but if it's an issue with the insert command, the it's probably an issue (or documentation issue) for clickhouse itself instead of clickhouse-cpp.
