### ISSUE TITLE
is there any ck-client project  that support  c++98

### ISSUE THREAD

**Issue by BrownHu** [ClickHouse/clickhouse-cpp#162]

**Comment by Enmk** [comment]
No, but why? C++98 is 24 years old, buggy and clumsy...
If you want a support for older C++ versions or even C/whatever, I suggest creating a C-wrapper for `Client`, `ClientOptions`, `Block` and `Column`. The column one is going to be the most tedious.

You can try to automate this process with [SWIG](http://www.swig.org/) or something similar.
