### ISSUE TITLE
Is Array(LowCardinality(String)) bugged?

### ISSUE THREAD

**Issue by li-darren** [ClickHouse/clickhouse-cpp#163]
I was using Array(String) and it seemed to work. I'd create a ColumnString and append all my strings and then in my ColumnArray, I would append as column.

However, with Array(LowCardinality(String)), I would change the database to this type, create a ColumnLowCardinalityT<ColumnString>, append all my values, and then append to the array as a column. This part is fine until I try to insert into my remote db, where I get the error

DB::Exception: Invalid version for DataTypeLowCardinality key column.

**Comment by Enmk** [comment]
Closed as a duplicate of: https://github.com/ClickHouse/clickhouse-cpp/issues/163

**Comment by li-darren** [comment]
duplicate of itself? did you tag the wrong post?
