### ISSUE TITLE
undefined reference to `clickhouse::Block::GetRowCount() const' occurs every time

### ISSUE THREAD

**Issue by jalopyalien** [ClickHouse/clickhouse-cpp#17]
I'm trying to run example and every time occurs next errors:
/usr/bin/ld: CMakeFiles/myTest.dir/main.cpp.o: in function `main::{lambda(clickhouse::Block const&)#1}::operator()(clickhouse::Block const&) const':
/root/CLionProjects/myTest/main.cpp:35: undefined reference to `clickhouse::Block::GetRowCount() const'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:36: undefined reference to `clickhouse::Block::operator[](unsigned long) const'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:36: undefined reference to `clickhouse::ColumnVector<unsigned long>::At(unsigned long) const'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:37: undefined reference to `clickhouse::Block::operator[](unsigned long) const'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:37: undefined reference to `clickhouse::ColumnString::At[abi:cxx11](unsigned long) const'
/usr/bin/ld: CMakeFiles/myTest.dir/main.cpp.o: in function `main':
/root/CLionProjects/myTest/main.cpp:9: undefined reference to `clickhouse::Client::Client(clickhouse::ClientOptions const&)'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:12: undefined reference to `clickhouse::Query::Query(char const*)'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:12: undefined reference to `clickhouse::Client::Execute(clickhouse::Query const&)'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:12: undefined reference to `clickhouse::Query::~Query()'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:16: undefined reference to `clickhouse::Block::Block()'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:19: undefined reference to `clickhouse::ColumnVector<unsigned long>::Append(unsigned long const&)'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:20: undefined reference to `clickhouse::ColumnVector<unsigned long>::Append(unsigned long const&)'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:23: undefined reference to `clickhouse::ColumnString::Append(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:24: undefined reference to `clickhouse::ColumnString::Append(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:26: undefined reference to `clickhouse::Block::AppendColumn(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<clickhouse::Column> const&)'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:27: undefined reference to `clickhouse::Block::AppendColumn(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<clickhouse::Column> const&)'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:29: undefined reference to `clickhouse::Client::Insert(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, clickhouse::Block const&)'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:16: undefined reference to `clickhouse::Block::~Block()'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:33: undefined reference to `clickhouse::Client::Select(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (clickhouse::Block const&)>)'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:43: undefined reference to `clickhouse::Query::Query(char const*)'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:43: undefined reference to `clickhouse::Client::Execute(clickhouse::Query const&)'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:43: undefined reference to `clickhouse::Query::~Query()'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:9: undefined reference to `clickhouse::Client::~Client()'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:12: undefined reference to `clickhouse::Query::~Query()'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:16: undefined reference to `clickhouse::Block::~Block()'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:43: undefined reference to `clickhouse::Query::~Query()'
/usr/bin/ld: /root/CLionProjects/myTest/main.cpp:9: undefined reference to `clickhouse::Client::~Client()'
/usr/bin/ld: CMakeFiles/myTest.dir/main.cpp.o: in function `std::shared_ptr<clickhouse::ColumnString> std::dynamic_pointer_cast<clickhouse::ColumnString, clickhouse::Column>(std::shared_ptr<clickhouse::Column> const&)':
/usr/include/c++/8/bits/shared_ptr.h:514: undefined reference to `typeinfo for clickhouse::ColumnString'
/usr/bin/ld: CMakeFiles/myTest.dir/main.cpp.o: in function `void __gnu_cxx::new_allocator<clickhouse::ColumnVector<unsigned long> >::construct<clickhouse::ColumnVector<unsigned long>>(clickhouse::ColumnVector<unsigned long>*)':
/usr/include/c++/8/ext/new_allocator.h:136: undefined reference to `clickhouse::ColumnVector<unsigned long>::ColumnVector()'
/usr/bin/ld: CMakeFiles/myTest.dir/main.cpp.o: in function `void __gnu_cxx::new_allocator<clickhouse::ColumnString>::construct<clickhouse::ColumnString>(clickhouse::ColumnString*)':
/usr/include/c++/8/ext/new_allocator.h:136: undefined reference to `clickhouse::ColumnString::ColumnString()'
collect2: error: ld returned 1 exit status
make[3]: *** [CMakeFiles/myTest.dir/build.make:84: myTest] Error 1
make[2]: *** [CMakeFiles/Makefile2:76: CMakeFiles/myTest.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/myTest.dir/rule] Error 2
make: *** [Makefile:118: myTest] Error 2

OS - clean installed Debian 10 amd64
gcc version 8.3.0
cmake version 3.13.4
CMAKE_CXX_STANDARD 14

I've built this library using official steps:
$ mkdir build .
$ cd build
$ cmake ..
$ make

After I'm trying main example and every time occurs problem with undefined reference.
Please help.

**Comment by ciberst** [comment]
everything works for me, you forgot, most likely, to link the library (clickhouse-cpp-lib) with your application

**Comment by jalopyalien** [comment]
I'm trying to add this library let me show my CMakeLists.txt:

cmake_minimum_required(VERSION 3.15)
project(myTest)
set(CMAKE_CXX_STANDARD 14)
include_directories(
        include
        /root/clickhouse-cpp/
)
add_executable(myTest main.cpp)

**Comment by ciberst** [comment]
after add_executable: 

```
target_link_libraries(myTest clickhouse-cpp-lib)
```

**Comment by jalopyalien** [comment]
After including I've received next error:

/usr/bin/ld: cannot find -lclickhouse-cpp-lib
collect2: error: ld returned 1 exit status
make[3]: *** [CMakeFiles/myTest.dir/build.make:84: myTest] Error 1
make[2]: *** [CMakeFiles/Makefile2:76: CMakeFiles/myTest.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/myTest.dir/rule] Error 2
make: *** [Makefile:118: myTest] Error 2

It seems need somewhere add path to this library(
but my path is /root/clickhouse-cpp/

**Comment by ciberst** [comment]
```
target_link_libraries(myTest /path/to/libclickhouse-cpp-lib.so)
```

**Comment by jalopyalien** [comment]
I've added correct path:
target_link_libraries(myTest /root/clickhouse-cpp/build/clickhouse/clickhouse-cpp-lib.so)

But after that I'm receiving:
make[3]: *** No rule to make target '/root/clickhouse-cpp/build/clickhouse/clickhouse-cpp-lib.so', needed by 'myTest'.  Stop.
make[2]: *** [CMakeFiles/Makefile2:76: CMakeFiles/myTest.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/myTest.dir/rule] Error 2
make: *** [Makefile:118: myTest] Error 2
It seems strange

**Comment by ciberst** [comment]
you can try my fork: https://github.com/ciberst/clickhouse-cpp
```
mkdir buld 
cd build 
cmake ..
make -j4
sudo make install 
```

CMakeLists.txt:
```
cmake_minimum_required(VERSION 2.8)
project(myTest)
set(CMAKE_CXX_STANDARD 17)
add_executable(${PROJECT_NAME} "main.cpp")
target_link_libraries(${PROJECT_NAME} clickhouse-cpp-lib)
```

**Comment by jalopyalien** [comment]
Thank you it works now!

Only one point which I've modified it my CMakeLists.txt:

```
cmake_minimum_required(VERSION 2.8)
project(myTest)
set(CMAKE_CXX_STANDARD 17)
add_executable(${PROJECT_NAME} "main.cpp")
target_link_libraries(${PROJECT_NAME} /usr/local/lib/libclickhouse-cpp-lib.so)
```

**Comment by peter279k** [comment]
> Thank you it works now!
> 
> Only one point which I've modified it my CMakeLists.txt:
> 
> ```
> cmake_minimum_required(VERSION 2.8)
> project(myTest)
> set(CMAKE_CXX_STANDARD 17)
> add_executable(${PROJECT_NAME} "main.cpp")
> target_link_libraries(${PROJECT_NAME} /usr/local/lib/libclickhouse-cpp-lib.so)
> ```

This file is saved my life when running the example code. Thanks!

**Comment by pkoosha** [comment]
I am having the same issue and this is how I am compiling it
``` g++ -I/usr/local/include -L/usr/local/lib/libclickhouse-cpp-lib.so -lclickhouse-cpp-lib --std=c++17 main.cpp -o main```

do you know what is the issue to fix?
