### ISSUE TITLE
The app crash when decode an empty low cardinality array

### ISSUE THREAD

**Issue by huyphams** [ClickHouse/clickhouse-cpp#178]
After this merge https://github.com/ClickHouse/clickhouse-cpp/pull/173 now I can decode the array of low cardinality, however it will crash when decoding an empty array.

1. Create a table with a column array of low cardinality.
```
CREATE TABLE array_lowcardinality
(
    `country` Array(LowCardinality(String)),
)
ENGINE = MergeTree
```

2. Insert some rows with an empty array.
3. Select from that table

=> Crash.

**Comment by arthurpassos** [comment]
Thanks for reporting this. Do you happen to have a full example? Or at least your select statement. I have tried using the existing unit tests with an extra empty array at the end and it's not crashing.

**Comment by Enmk** [comment]
Seems to be resolved and tested. Feel free to reopen with an example.

**Comment by huyphams** [comment]
I'm still getting this error. When I connect to the ClickHouse default system database and then run this query below:

```
SELECT roles FROM "system"."session_log" LIMIT 2 OFFSET 0;
```

I will get this error:

`can't load column 'roles' of type Array(LowCardinality(String))`

Note some weird behaviors:

1. If the first object is an empty array, it will crash the app.
2. If the first object is not empty (ex: has 1 element), it works.

I think it has something to do with the format where the first object is an empty array.
