### ISSUE TITLE
error C2664:  cannot convert argument 5 from 'char [255]' to 'LPWSTR'

### ISSUE THREAD

**Issue by JonLiu1993** [ClickHouse/clickhouse-cpp#185]
Hello
I encountered an error when updating clickhouse-cpp to the latest version:

````
\clickhouse\base\socket.cpp(30): error C2664: 'DWORD FormatMessageW(DWORD,LPCVOID,DWORD,DWORD,LPWSTR,DWORD,va_list *)': cannot convert argument 5 from 'char [255]' to 'LPWSTR'
D:\buildtrees\clickhouse-cpp\src\677f0c1b1e-c94ae94bd9.clean\clickhouse\base\socket.cpp(30): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winbase.h(2471): note: see declaration of 'FormatMessageW'
D:\buildtrees\clickhouse-cpp\src\677f0c1b1e-c94ae94bd9.clean\clickhouse\base\socket.cpp(31): error C3536: 'len': cannot be used before it is initialized
````
    auto len = FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM, nullptr, static_cast<DWORD>(c), 0, error, sizeof(error), nullptr);

I investigated and found that should use wide literal here 
````
char error[UINT8_MAX]->>wchar_t error[UINT8_MAX];
````
so I try modified and install again, but still failed:
````
F:\test\vcpkg\buildtrees\clickhouse-cpp\src\677f0c1b1e-46b022203f\clickhouse\base\socket.cpp(41): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'std::string'
````
I'm stuck, hope someone can give me some advice, I'd appreciate it!

**Comment by Enmk** [comment]
Thanks for a report! unfortunately we are not testing for all possible windows build options, so this error got undetected by CI/CD. Also I don't have a Windows machine at hand, so I need a bit of help from your side to verify/fix it.

Could you please specify your build options? I assume you are doing a wide-char build, am I right?

You may want to try doing replacing `windowsErrorCategory::message(int c)` implementation with:
```
std::string windowsErrorCategory::message(int c) const {
    WCHAR error[UINT8_MAX];
    auto len = FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM, nullptr, static_cast<DWORD>(c), 0, error, sizeof(error), nullptr);
    if (len == 0) {
        return "unknown";
    }
    while (len && (error[len - 1] == '\r' || error[len - 1] == '\n')) {
        --len;
    }
    return std::string(error, len);
}
```

If that fixes the issue for you, please submit a PR.

**Comment by JonLiu1993** [comment]
@Enmk ,Thanks for your help, when I change following your davice, it said 
````
F:\Feature-test\clickhouse-cpp\vcpkg\buildtrees\clickhouse-cpp\src\677f0c1b1e-c94ae94bd9\clickhouse\base\socket.cpp(37): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'std::string'
````
Do you have any advice?

**Comment by Enmk** [comment]
You should convert Windows unicode text into utf8 and then create a std::string from that, you may want to try something like this: https://stackoverflow.com/a/7561991
