### ISSUE TITLE
Library not working

### ISSUE THREAD

**Issue by sharp-0000ff** [ClickHouse/clickhouse-cpp#194]
Hi, everyone.
I use ubuntu 18.04
I copied the repository and built it, but when I run example code from readme I get a lot of errors.
![image](https://user-images.githubusercontent.com/25490876/176993317-c57e13e1-6e46-4f4d-a882-ef594020467f.png)
![image](https://user-images.githubusercontent.com/25490876/176993348-cd4e34ad-ad9c-4776-9a18-766656cf30b6.png)
![image](https://user-images.githubusercontent.com/25490876/176993362-56933111-a1b5-44bc-9a3c-185f068fb55c.png)
![image](https://user-images.githubusercontent.com/25490876/176993384-73343eb1-cebe-4e04-bf69-b065e4b81e07.png)
![image](https://user-images.githubusercontent.com/25490876/176993397-565baeba-bb24-4867-accb-5cc31899c967.png)
![image](https://user-images.githubusercontent.com/25490876/176993420-d8bba172-9e40-4fcb-8434-f09bf867b841.png)
What am I doing wrong? help me

**Comment by filimonov** [comment]
Some very old compile may be?  Check ci/cd build scenario https://github.com/ClickHouse/clickhouse-cpp/blob/master/.github/workflows/linux.yml

**Comment by sharp-0000ff** [comment]
@filimonov Thanks, using "g++ -std=c++17 example.cpp" helped solve the problem, but the last error didn't go away.
![image](https://user-images.githubusercontent.com/25490876/177263078-8bc8ccaf-b29d-4100-8aab-d693e35910fd.png)
How to solve this problem?
