### ISSUE TITLE
windows connection database crash

### ISSUE THREAD

**Issue by inaryart** [ClickHouse/clickhouse-cpp#195]
I bet no one in the real world has used clickhouse-cpp on windows, not even for testing.

Using the following code on windows results in an error code: `WSAHOST_NOT_FOUND`
https://github.com/ClickHouse/clickhouse-cpp/blob/de70d975a19655e64d6d3037dd1402be02442c08/clickhouse/base/socket.cpp#L194

So it will crash here
https://github.com/ClickHouse/clickhouse-cpp/blob/de70d975a19655e64d6d3037dd1402be02442c08/clickhouse/base/socket.cpp#L200

we need
```
#if defined(_unix_)
    if (!Singleton<LocalNames>()->IsLocalName(host)) {
        // https://linux.die.net/man/3/getaddrinfo
        // If hints.ai_flags includes the AI_ADDRCONFIG flag,
        // then IPv4 addresses are returned in the list pointed to by res only
        // if the local system has at least one IPv4 address configured,
        // and IPv6 addresses are only returned if the local system
        // has at least one IPv6 address configured.
        // The loopback address is not considered for this case
        // as valid as a configured address.
        hints.ai_flags |= AI_ADDRCONFIG;
    }
#endif
```

At the same time, I don't know why windows can never receive database messages here,
https://github.com/ClickHouse/clickhouse-cpp/blob/de70d975a19655e64d6d3037dd1402be02442c08/clickhouse/base/socket.cpp#L335

so inevitably it crashes in the code behind
https://github.com/ClickHouse/clickhouse-cpp/blob/de70d975a19655e64d6d3037dd1402be02442c08/clickhouse/base/socket.cpp#L342

By the way I am connecting to the remote ip

**Comment by filimonov** [comment]
Can you create a pull request with desired changes? (also with tests if possible)

**Comment by filimonov** [comment]
> I bet no one in the real world has used clickhouse-cpp on windows, not even for testing.

How much did you bet? where can i get my money? :)

**Comment by filimonov** [comment]
BTW what exception do you get after `recv`? It should be printed by  getSocketErrorCode
