### ISSUE TITLE
Add the reserve interface to reduce the number of memory allocations

### ISSUE THREAD

**Issue by King-Authur** [ClickHouse/clickhouse-cpp#201]
The clickhouse writing service knows the number of rows of data when accumulating data. At this time, we can directly calculate the memory space they need, and allocate them directly through Reserve, which can reduce the number of memory allocations and reduce the time consuming when constructing columns.

**Comment by Enmk** [comment]
How do you plan to implement Reserve for ColumnString or ColumnLowCardinality?

**Comment by Enmk** [comment]
Closed by #341 and #330
