### ISSUE TITLE
How to set TIMEZONE

### ISSUE THREAD

**Issue by arfaa-23** [ClickHouse/clickhouse-cpp#204]
Hello, I try set timezone to DateTime64:
```
auto timestamp_ = std::make_shared<clickhouse::ColumnDateTime64>(3, "Europe/Amsterdam");
timestamp_->Append(timestamp);
_block.AppendColumn("timestamp", timestamp_);
```
but it not works, what is wrong?

**Comment by Enmk** [comment]
Could you please define "not works"? Do you expect values stored in column to be transformed? Or maybe some other result when you execute `SELECT`?
