### ISSUE TITLE
memory copy ---- void ColumnString::Append(ColumnRef column)

### ISSUE THREAD

**Issue by 1261385937** [ClickHouse/clickhouse-cpp#207]
The `void ColumnString::Append(ColumnRef column)`  also has memory copy
<br> BTW ,  In my scenario,  the given column data (huge) will be no useful  after calling this interface. 
<br> Here is a complicated inherit. If i make a overload interface, will be a lot of modification.  
<br> @Enmk  , any suggest ?
<br> I will submit a PR this weekend.

**Comment by Enmk** [comment]
Addressed in https://github.com/ClickHouse/clickhouse-cpp/pull/212

**Comment by 1261385937** [comment]
@Enmk  please review #237<br>
Our scene is heavy writing (200000*1k ~ 200MB per second) <br>
Perf top is memory malloc and free <br>
I want to keep our code same with official lib， so any assist, please @1261385937
