### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by GilbertoTheMighty** [ClickHouse/clickhouse-cpp#211]
After building and installing [clickhouse-cpp](https://github.com/ClickHouse/clickhouse-cpp)
I'm trying to run example code from main page to execute test query but it misses some includes.
`clickhouse/types/types.h:3:10: fatal error: absl/numeric/int128.h: No such file or directory
    3 | #include "absl/numeric/int128.h"`
I'm linking as a static lib.
Is there any guide how to use this properly?

**Comment by Hyrikan** [comment]
I also had some troubles finding the correct way of using this client in my project. But i managed to get it running. Here are my steps:
First, i copied over the three contrib libs and the clickhouse-client lib into my project.
Second, i copied over the source folders of the contribs and clickhouse-client. We only need the header files, but i was too lazy to fish the headers out of the source dirs.
You could also copy the libs into your systems lib dir and the headers into your systems header dir. But i kept it local.
Third, i added the folder with the libs as link-directories and the folders with the copied source folders as include-directory, so my build program finds them.
If you use cmake, that would be link_directories() and include_directories(). With plain compiler, add them as flags.

Hope this helps.

**Comment by peter279k** [comment]
I also have the same issue and my solutions are as follows:

For Ubuntu,

- Firstly, using the `git clone `https://github.com/abseil/abseil-cpp` to clone the repository. This is the source of `absl` C++ library.
- Running the `cd abseil-cpp/`, `mkdir build` and `cd build` commands.
- Running the `cmake ..`, `make` and `sudo make install` commands to configure, compile and install this C++ library.
- Finally, all of these C++ dynamic link libraries (header files) are installed in the system-wide in your Linux Ubuntu 18.04 operating system.
  - They're located in the `/usr/local/include/absl/` directory.

**Comment by sjdhanasekaran** [comment]
@Enmk @peter279k Any one build with out external absl or with contrib/absl is that working ?

**Comment by peter279k** [comment]
@sjdhanasekaran. The issue seems to be fixed.
According to the [sample codes](https://github.com/ClickHouse/clickhouse-cpp?tab=readme-ov-file#example-application-build-with-clickhouse-cpp), I compile and build successfully with the contrib/absl.

Here are my commands I run in the fresh Ubuntu 20.04 and we assume that the ClickHouse server has been installed:

```sh
$ apt-get update
$ apt-get install build-essential cmake ninja-build -y
$ mkdir clickhouse-app && cd clickhouse-app && git init
$ git submodule add https://github.com/ClickHouse/clickhouse-cpp.git contribs/clickhouse-cpp
$ touch app.cpp
$ cat app.cpp
#include <iostream>
#include <clickhouse/client.h>

using namespace clickhouse;

int main()
{
    /// Initialize client connection.
    Client client(ClientOptions().SetHost("localhost"));

    /// Create a table.
    client.Execute("CREATE TABLE IF NOT EXISTS default.numbers (id UInt64, name String) ENGINE = Memory");

    /// Insert some values.
    {
        Block block;

        auto id = std::make_shared<ColumnUInt64>();
        id->Append(1);
        id->Append(7);

        auto name = std::make_shared<ColumnString>();
        name->Append("one");
        name->Append("seven");

        block.AppendColumn("id"  , id);
        block.AppendColumn("name", name);

        client.Insert("default.numbers", block);
    }

    /// Select values inserted in the previous step.
    client.Select("SELECT id, name FROM default.numbers", [] (const Block& block)
        {
            for (size_t i = 0; i < block.GetRowCount(); ++i) {
                std::cout << block[0]->As<ColumnUInt64>()->At(i) << " "
                          << block[1]->As<ColumnString>()->At(i) << "\n";
            }
        }
    );

    /// Delete table.
    client.Execute("DROP TABLE default.numbers");

    return 0;
}
$ touch CMakeLists.txt
$ cat CMakeLists.txt
cmake_minimum_required(VERSION 3.12)
project(application-example)

set(CMAKE_CXX_STANDARD 17)

add_subdirectory(contribs/clickhouse-cpp)

add_executable(${PROJECT_NAME} "app.cpp")

target_include_directories(${PROJECT_NAME} PRIVATE contribs/clickhouse-cpp/ contribs/clickhouse-cpp/contrib/absl)

target_link_libraries(${PROJECT_NAME} PRIVATE clickhouse-cpp-lib)
$ rm -rf build && cmake -B build -S . && cmake --build build -j32
......
[ 94%] Building CXX object contribs/clickhouse-cpp/clickhouse/CMakeFiles/clickhouse-cpp-lib.dir/query.cpp.o
[ 94%] Building CXX object contribs/clickhouse-cpp/clickhouse/CMakeFiles/clickhouse-cpp-lib.dir/block.cpp.o
[ 96%] Building CXX object contribs/clickhouse-cpp/clickhouse/CMakeFiles/clickhouse-cpp-lib.dir/client.cpp.o
[ 97%] Linking CXX static library libclickhouse-cpp-lib.a
[ 97%] Built target clickhouse-cpp-lib
Scanning dependencies of target application-example
[ 98%] Building CXX object CMakeFiles/application-example.dir/app.cpp.o
[100%] Linking CXX executable application-example
[100%] Built target application-example
$ ./build/application-example
1 one
7 seven
```

I hope these above outputs may be helpful for you :).

**Comment by sjdhanasekaran** [comment]
@peter279k Thanks.
