### ISSUE TITLE
How to compile in Windows Environment？

### ISSUE THREAD

**Issue by wzz1234wzz** [ClickHouse/clickhouse-cpp#213]
I performed the following steps:
D:\>cd thirdCompile
D:\thirdCompile>git clone https://github.com/ClickHouse/clickhouse-cpp.git
D:\thirdCompile>cd clickhouse-cpp
D:\thirdCompile\clickhouse-cpp>mkdir build
D:\thirdCompile\clickhouse-cpp>cd build
D:\thirdCompile\clickhouse-cpp\build>cmake ..  -G "Unix Makefiles"
D:\thirdCompile\clickhouse-cpp\build>make

Then the following error was reported:
D:/thirdCompile/clickhouse-cpp/clickhouse/base/socket.cpp: In member function 'virtual void clickhouse::SocketFactory::sleepFor(const milliseconds&)':
D:/thirdCompile/clickhouse-cpp/clickhouse/base/socket.cpp:239:10: error: 'std::this_thread' has not been declared
     std::this_thread::sleep_for(duration);
          ^~~~~~~~~~~
make[2]: *** [clickhouse/CMakeFiles/clickhouse-cpp-lib.dir/build.make:137: clickhouse/CMakeFiles/clickhouse-cpp-lib.dir/base/socket.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:156: clickhouse/CMakeFiles/clickhouse-cpp-lib.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

Note:
my compilation environment：
gcc version 8.1.0 (x86_64-win32-seh-rev0, Built by MinGW-W64 project)
cmake version 3.20.1

**Comment by Enmk** [comment]
Please follow [`.github/workflows/Windows.yml`](https://github.com/ClickHouse/clickhouse-cpp/blob/master/.github/workflows/windows_mingw.yml) for instructions.

**Comment by Enmk** [comment]
If you have any questions/additions or fixes, please open a PR that modifies README.md
