### ISSUE TITLE
Error in running example

### ISSUE THREAD

**Issue by wzz1234wzz** [ClickHouse/clickhouse-cpp#214]
When compiling the examples in the warehouse in centos7 environment, the following error is reported：

In file included from /opt/thirdpart/ck/include/clickhouse/columns/column.h:3,
                 from /opt/thirdpart/ck/include/clickhouse/block.h:3,
                 from /opt/thirdpart/ck/include/clickhouse/query.h:3,
                 from /opt/thirdpart/ck/include/clickhouse/client.h:3,
                 from /home/centos/ckTest/src/main.cpp:1:
/opt/thirdpart/ck/include/clickhouse/columns/../types/types.h:215:10: error: 'string_view' in namespace 'std' does not name a type
  215 |     std::string_view GetEnumName(int16_t value) const;
      |          ^~~~~~~~~~~
/opt/thirdpart/ck/include/clickhouse/columns/../types/types.h:215:5: note: 'std::string_view' is only available from C++17 onwards
  215 |     std::string_view GetEnumName(int16_t value) const;
      |     ^~~
/opt/thirdpart/ck/include/clickhouse/columns/../types/types.h:221:56: error: 'string_view' is not a member of 'std'
  221 |     using ValueToNameType     = std::map<int16_t, std::string_view>;
      |                                                        ^~~~~~~~~~~
/opt/thirdpart/ck/include/clickhouse/columns/../types/types.h:221:56: note: 'std::string_view' is only available from C++17 onwards
/opt/thirdpart/ck/include/clickhouse/columns/../types/types.h:221:56: error: 'string_view' is not a member of 'std'
/opt/thirdpart/ck/include/clickhouse/columns/../types/types.h:221:56: note: 'std::string_view' is only available from C++17 onwards
/opt/thirdpart/ck/include/clickhouse/columns/../types/types.h:221:67: error: template argument 2 is invalid
  221 |     using ValueToNameType     = std::map<int16_t, std::string_view>;
      |                                                                   ^
/opt/thirdpart/ck/include/clickhouse/columns/../types/types.h:221:67: error: template argument 4 is invalid
/opt/thirdpart/ck/include/clickhouse/columns/../types/types.h:223:33: error: 'ValueToNameType' does not name a type
  223 |     using ValueToNameIterator = ValueToNameType::const_iterator;
      |                                 ^~~~~~~~~~~~~~~
/opt/thirdpart/ck/include/clickhouse/columns/../types/types.h:225:5: error: 'ValueToNameType' does not name a type
  225 |     ValueToNameType value_to_name_;
      |     ^~~~~~~~~~~~~~~
/opt/thirdpart/ck/include/clickhouse/columns/../types/types.h:229:5: error: 'ValueToNameIterator' does not name a type
  229 |     ValueToNameIterator BeginValueToName() const;
      |     ^~~~~~~~~~~~~~~~~~~
/opt/thirdpart/ck/include/clickhouse/columns/../types/types.h:230:5: error: 'ValueToNameIterator' does not name a type
  230 |     ValueToNameIterator EndValueToName() const;
      |     ^~~~~~~~~~~~~~~~~~~
In file included from /opt/thirdpart/ck/include/clickhouse/columns/column.h:4,
                 from /opt/thirdpart/ck/include/clickhouse/block.h:3,
                 from /opt/thirdpart/ck/include/clickhouse/query.h:3,
                 from /opt/thirdpart/ck/include/clickhouse/client.h:3,
                 from /home/centos/ckTest/src/main.cpp:1:
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:21:27: error: 'string_view' in namespace 'std' does not name a type
   21 |     using DataType = std::string_view;
      |                           ^~~~~~~~~~~
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:21:22: note: 'std::string_view' is only available from C++17 onwards
   21 |     using DataType = std::string_view;
      |                      ^~~
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:24:11: error: 'DataType' does not name a type
   24 |     const DataType data;
      |           ^~~~~~~~
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:40:31: error: 'DataType' has not been declared
   40 |     ItemView(Type::Code type, DataType data)
      |                               ^~~~~~~~
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:78:17: error: 'string_view' in namespace 'std' does not name a type
   78 |     inline std::string_view AsBinaryData() const {
      |                 ^~~~~~~~~~~
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:78:12: note: 'std::string_view' is only available from C++17 onwards
   78 |     inline std::string_view AsBinaryData() const {
      |            ^~~
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:83:47: error: 'DataType' has not been declared
   83 |     static void ValidateData(Type::Code type, DataType data);
      |                                               ^~~~~~~~
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h: In member function 'auto clickhouse::ItemView::ConvertToStorageValue(const T&)':
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:29:12: warning: 'if constexpr' only available with '-std=c++17' or '-std=gnu++17'
   29 |         if constexpr (std::is_same_v<std::string_view, T> || std::is_same_v<std::string, T>) {
      |            ^~~~~~~~~
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:29:28: error: 'is_same_v' is not a member of 'std'; did you mean 'is_same'?
   29 |         if constexpr (std::is_same_v<std::string_view, T> || std::is_same_v<std::string, T>) {
      |                            ^~~~~~~~~
      |                            is_same
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:29:43: error: 'string_view' is not a member of 'std'
   29 |         if constexpr (std::is_same_v<std::string_view, T> || std::is_same_v<std::string, T>) {
      |                                           ^~~~~~~~~~~
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:29:43: note: 'std::string_view' is only available from C++17 onwards
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:29:57: error: expected primary-expression before '>' token
   29 |         if constexpr (std::is_same_v<std::string_view, T> || std::is_same_v<std::string, T>) {
      |                                                         ^
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:29:59: error: expected primary-expression before '||' token
   29 |         if constexpr (std::is_same_v<std::string_view, T> || std::is_same_v<std::string, T>) {
      |                                                           ^~
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:29:67: error: 'is_same_v' is not a member of 'std'; did you mean 'is_same'?
   29 |         if constexpr (std::is_same_v<std::string_view, T> || std::is_same_v<std::string, T>) {
      |                                                                   ^~~~~~~~~
      |                                                                   is_same
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:29:88: error: expected primary-expression before ',' token
   29 |         if constexpr (std::is_same_v<std::string_view, T> || std::is_same_v<std::string, T>) {
      |                                                                                        ^
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:29:91: error: expected primary-expression before '>' token
   29 |         if constexpr (std::is_same_v<std::string_view, T> || std::is_same_v<std::string, T>) {
      |                                                                                           ^
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:29:92: error: expected primary-expression before ')' token
   29 |         if constexpr (std::is_same_v<std::string_view, T> || std::is_same_v<std::string, T>) {
      |                                                                                            ^
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:30:25: error: 'string_view' is not a member of 'std'
   30 |             return std::string_view{t};
      |                         ^~~~~~~~~~~
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:30:25: note: 'std::string_view' is only available from C++17 onwards
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:30:36: error: expected ';' before '{' token
   30 |             return std::string_view{t};
      |                                    ^
      |                                    ;
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:30:38: error: expected ';' before '}' token
   30 |             return std::string_view{t};
      |                                      ^
      |                                      ;
/opt/thirdpart/ck/include/clickhouse/columns/../columns/itemview.h:31:19: warning: 'if constexpr' only available with '-std=c++17' or '-std=gnu++17'
   31 |         } else if constexpr (std::is_fundamental_v<T> || std::is_same_v<Int128, std::decay_t<T>>) {
      |                   ^~~~~~~~~

**Comment by wzz1234wzz** [comment]
gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)
cmake version 3.17.3

**Comment by Enmk** [comment]
Hi @wzz1234wzz ! Thank you for reporting, right now we don't have any CentOS-based checks in CI/CD, so you are welcome to contribute. For inspiration you may want to see:
- https://github.com/ClickHouse/clickhouse-odbc/blob/master/.github/workflows/Docker.yml
- https://github.com/ClickHouse/clickhouse-odbc/blob/master/test/docker/Dockerfile

**Comment by peter279k** [comment]
I prepare the fresh and clean `CentOS 7` operating system and running the following commands to prepare compilation environment:

```bash
[root@centos-s-4vcpu-8gb-amd-sgp1-01 ~]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
[root@centos-s-4vcpu-8gb-amd-sgp1-01 ~]# yum update
......
  xz-libs.x86_64 0:5.2.2-2.el7_9
  zlib.x86_64 0:1.2.7-20.el7_9

Complete!
[root@centos-s-4vcpu-8gb-amd-sgp1-01 ~]# yum install -y git wget vim
[root@centos-s-4vcpu-8gb-amd-sgp1-01 ~]# yum install -y centos-release-scl
[root@centos-s-4vcpu-8gb-amd-sgp1-01 ~]# yum install devtoolset-7-gcc-c++ --enablerepo='centos-sclo-rh'
[root@centos-s-4vcpu-8gb-amd-sgp1-01 ~]# scl enable devtoolset-7 'bash'
[root@centos-s-4vcpu-8gb-amd-sgp1-01 ~]# g++ --version
g++ (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
[root@centos-s-4vcpu-8gb-amd-sgp1-01 ~]# wget https://cmake.org/files/v3.12/cmake-3.12.3.tar.gz
[root@centos-s-4vcpu-8gb-amd-sgp1-01 ~]# tar zxvf cmake-3.*
[root@centos-s-4vcpu-8gb-amd-sgp1-01 ~]# cd cmake-3.*
[root@centos-s-4vcpu-8gb-amd-sgp1-01 cmake-3.12.3]# ./bootstrap --prefix=/usr/local
[root@centos-s-4vcpu-8gb-amd-sgp1-01 cmake-3.12.3]# make -j$(nproc)
[root@centos-s-4vcpu-8gb-amd-sgp1-01 cmake-3.12.3]# make install
[root@centos-s-4vcpu-8gb-amd-sgp1-01 cmake-3.12.3]# cmake --version
cmake version 3.12.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
[root@centos-s-4vcpu-8gb-amd-sgp1-01 cmake-3.12.3]#
```

Then run the following commands to download, configure, compile and install required C++ libraries:

```sh
[root@centos-s-4vcpu-8gb-amd-sgp1-01 ~]# git clone https://github.com/abseil/abseil-cpp
[root@centos-s-4vcpu-8gb-amd-sgp1-01 ~]# cd abseil-cpp/
[root@centos-s-4vcpu-8gb-amd-sgp1-01 abseil-cpp]# mkdir build/
[root@centos-s-4vcpu-8gb-amd-sgp1-01 abseil-cpp]# cd build/
[root@centos-s-4vcpu-8gb-amd-sgp1-01 build]# cmake ..
[root@centos-s-4vcpu-8gb-amd-sgp1-01 build]# make
[root@centos-s-4vcpu-8gb-amd-sgp1-01 build]# make install
[root@centos-s-4vcpu-8gb-amd-sgp1-01 ~]# git clone https://github.com/ClickHouse/clickhouse-cpp
[root@centos-s-4vcpu-8gb-amd-sgp1-01 ~]# cd clickhouse-cpp/
[root@centos-s-4vcpu-8gb-amd-sgp1-01 clickhouse-cpp]# mkdir build/
[root@centos-s-4vcpu-8gb-amd-sgp1-01 clickhouse-cpp]# cd build/
[root@centos-s-4vcpu-8gb-amd-sgp1-01 build]# cmake ..
[root@centos-s-4vcpu-8gb-amd-sgp1-01 build]# make
[root@centos-s-4vcpu-8gb-amd-sgp1-01 build]# make install
```

Running the following example codes and saved to the `clickhouse.cpp` file:

```cpp
#include <clickhouse/client.h>

using namespace clickhouse;

/// Initialize client connection.
Client client(ClientOptions().SetHost("localhost"));

/// Create a table.
client.Execute("CREATE TABLE IF NOT EXISTS test.numbers (id UInt64, name String) ENGINE = Memory");

/// Insert some values.
{
    Block block;

    auto id = std::make_shared<ColumnUInt64>();
    id->Append(1);
    id->Append(7);

    auto name = std::make_shared<ColumnString>();
    name->Append("one");
    name->Append("seven");

    block.AppendColumn("id"  , id);
    block.AppendColumn("name", name);

    client.Insert("test.numbers", block);
}

/// Select values inserted in the previous step.
client.Select("SELECT id, name FROM test.numbers", [] (const Block& block)
    {
        for (size_t i = 0; i < block.GetRowCount(); ++i) {
            std::cout << block[0]->As<ColumnUInt64>()->At(i) << " "
                      << block[1]->As<ColumnString>()->At(i) << "\n";
        }
    }
);

/// Delete table.
client.Execute("DROP TABLE test.numbers");
```

Creating the following `CMakeLists.txt` file:

```sh
cmake_minimum_required(VERSION 3.0)
project(clickhouse-example)
set(CMAKE_CXX_STANDARD 17)
add_executable(${PROJECT_NAME} "clickhouse.cpp")
target_link_libraries(${PROJECT_NAME} /usr/local/lib/libclickhouse-cpp-lib.so)
```

Running the `cmake .` and `make`. And it will get the following message:

```sh
[root@centos-s-4vcpu-8gb-amd-sgp1-01 ~]# cmake .
[root@centos-s-4vcpu-8gb-amd-sgp1-01 ~]# make
[ 50%] Building CXX object CMakeFiles/clickhouse-example.dir/clickhouse.cpp.o
/root/clickhouse.cpp:9:1: error: ‘client’ does not name a type
 client.Execute("CREATE TABLE IF NOT EXISTS default.numbers (id UInt64, name String) ENGINE = Memory");
 ^~~~~~
/root/clickhouse.cpp:12:1: error: expected unqualified-id before ‘{’ token
 {
 ^
/root/clickhouse.cpp:30:1: error: ‘client’ does not name a type
 client.Select("SELECT id, name FROM default.numbers", [] (const Block& block)
 ^~~~~~
/root/clickhouse.cpp:37:1: error: expected unqualified-id before ‘)’ token
 );
 ^
/root/clickhouse.cpp:40:1: error: ‘client’ does not name a type
 client.Execute("DROP TABLE default.numbers");
 ^~~~~~
make[2]: *** [CMakeFiles/clickhouse-example.dir/clickhouse.cpp.o] Error 1
make[1]: *** [CMakeFiles/clickhouse-example.dir/all] Error 2
make: *** [all] Error 2
[root@centos-s-4vcpu-8gb-amd-sgp1-01 ~]#
```

It seems that the following code is not correct and letting above example codes change into:

```cpp
#include <iostream>
#include <clickhouse/client.h>

using namespace clickhouse;

int main()
{
    /// Initialize client connection.
    Client client(ClientOptions().SetHost("localhost"));

    /// Create a table.
    client.Execute("CREATE TABLE IF NOT EXISTS default.numbers (id UInt64, name String) ENGINE = Memory");

    /// Insert some values.
    {
        Block block;

        auto id = std::make_shared<ColumnUInt64>();
        id->Append(1);
        id->Append(7);

        auto name = std::make_shared<ColumnString>();
        name->Append("one");
        name->Append("seven");

        block.AppendColumn("id"  , id);
        block.AppendColumn("name", name);

        client.Insert("default.numbers", block);
    }

    /// Select values inserted in the previous step.
    client.Select("SELECT id, name FROM default.numbers", [] (const Block& block)
        {
            for (size_t i = 0; i < block.GetRowCount(); ++i) {
                std::cout << block[0]->As<ColumnUInt64>()->At(i) << " "
                          << block[1]->As<ColumnString>()->At(i) << "\n";
            }
        }
    );

    /// Delete table.
    client.Execute("DROP TABLE default.numbers");

    return 0;
}
```

Then run the `make` commands again. It will compile the sample C++ codes successfully:

```sh
[root@centos-s-4vcpu-8gb-amd-sgp1-01 ~]# make
Scanning dependencies of target clickhouse-example
[ 50%] Building CXX object CMakeFiles/clickhouse-example.dir/clickhouse.cpp.o
[100%] Linking CXX executable clickhouse-example
[100%] Built target clickhouse-example
[root@centos-s-4vcpu-8gb-amd-sgp1-01 ~]#
```
