### ISSUE TITLE
ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by gcnote** [ClickHouse/clickhouse-cpp#218]
macOS 12.5 Apple M1 Pro
test code :
<img width="820" alt="image" src="https://user-images.githubusercontent.com/10720842/193229731-e2d3f8cd-10a3-4d40-9bd6-21448603a0ea.png">

when build code,  error is:      ld: symbol(s) not found for architecture arm64

this error is only display when std::cout  ColumnDecimal column

**Comment by 1261385937** [comment]
Any pr is welcome

**Comment by Enmk** [comment]
Hi @gcnote ! Thank you for reporting, right now M1 on macOS is not supported as GitHub runner, so it is kind of hard to fix that. 
So if you want this issue fixed, please submit a PR.

Also, it could be very interesting to run built in tests on M1: you need to configure with `cmake ... -DBUILD_TESTS=ON`)

**Comment by Enmk** [comment]
@gcnote are you willing to take this as a task and fix it? If no, I would have to close it -- since I don't have access to M1 mac at the moment and can't fix it myself.

**Comment by gcnote** [comment]
@Enmk Thank you for answer, you can close it. 
By the way, does it support macOS with Intel core?

**Comment by Enmk** [comment]
@gcnote could you please describe a workaround/fix or whatever helped you to resolve the issue?
Yes, it clickhouse-cpp works on macOS+Intel, and there is a workflow for that: https://github.com/ClickHouse/clickhouse-cpp/blob/master/.github/workflows/macos.yml

**Comment by gcnote** [comment]
您好，您发的邮件我已收到，谢谢！！！

**Comment by gcnote** [comment]
您好，您发的邮件我已收到，谢谢！！！
