### ISSUE TITLE
[feature request] Conan support

### ISSUE THREAD

**Issue by itrofimow** [ClickHouse/clickhouse-cpp#225]
Even though it's pretty convenient to build because of the great documentation you guys provide, would be awesome if the library could be used as a conan package.

For instance, we are trying to package [userver framework](https://github.com/userver-framework/userver) into conan, and as of now clickhouse driver is missing from it, because it uses the clickhouse-cpp library underneath, which is not present in cci

**Comment by itrofimow** [comment]
Seems like it's a WIP already https://github.com/ClickHouse/clickhouse-cpp/pull/219

**Comment by Jihadist** [comment]
Huston, we have had a problem...
This fix for clang https://github.com/ClickHouse/clickhouse-cpp/blob/master/CMakeLists.txt#L43-L64 works correctly when you build clickhouse-cpp from cmakelists. But if we install the package, we'll drop this fix. So we cannot compile executable depends on clickhouse-cpp. For example, conan test_package cannot be compiled while lib compiles ok https://c3i.jfrog.io/c3i/misc/logs/pr/17312/10-linux-clang/clickhouse-cpp/2.4.0//afdaed6298b1f61f6cd8e81454e1f8751c488a3f-test.txt
What should be better, manage this from conan recipe or move this fix to clang_fix.cmake and include everywhere?
Releted conan pr https://github.com/conan-io/conan-center-index/pull/17312
P.S. This issue does not relate to conan, we'll have the same with _cmake install_ command
cc @Enmk

**Comment by cthulhu-irl** [comment]
It seems clickhouse-cpp exists on conan. maybe close this issue?

**Comment by Jihadist** [comment]
fyi @Enmk, close please
