### ISSUE TITLE
How to correct clean Block class variable?

### ISSUE THREAD

**Issue by jalopyalien** [ClickHouse/clickhouse-cpp#23]
Based on main page example :
```
{
    Block block;
    auto id = std::make_shared<ColumnUInt64>();
    id->Append(1);
    id->Append(7);
    auto name = std::make_shared<ColumnString>();
    name->Append("one");
    name->Append("seven");
    block.AppendColumn("id"  , id);
    block.AppendColumn("name", name);
    client.Insert("test.numbers", block);
}
```
I'm trying to clean variable 'block' and cannot execute it. Due to documentation delete (memset) command is not supporting and occurring next error : 

> free(): invalid size

When I'm using it in cycle (instead 1, 7, "one", "seven" I'm using variables) I'm getting duplicate values in my db. Could you please advise how to correct clean it?

**Comment by jalopyalien** [comment]
WA was found by adding next strings at the end of main example:

```
id->Clear();
name->Clear();
```

**Comment by Enmk** [comment]
You are not expected to clear the block, instead you may want to 
- re-create a new one every time.
- `Clear()` on each column individually and then `RefreshRowCount()` on a block after you have inserted all data into columns.
- insert all your values into columns in a loop, and then create and send a block

The latter one is the recommended approach.
