### ISSUE TITLE
error: invalid conversion from 'const void*' to 'PVOID' {aka 'void*'} [-fpermissive]

### ISSUE THREAD

**Issue by gcnote** [ClickHouse/clickhouse-cpp#234]
OS: windows 11
CPU: 11th Gen Intel(R) Core(TM) i5
mingw64-seh-posix 8.1.0
cmake 3.24.2

step 1 - cmake:
![image](https://user-images.githubusercontent.com/10720842/198182008-c5029b6f-790f-4a6e-9a2c-2dc9c0711dcf.png)

step 2 - make:
![image](https://user-images.githubusercontent.com/10720842/198182204-573f52de-953f-4062-9522-bbf29554106a.png)

**Comment by Enmk** [comment]
Hi @gcnote, thank you for report! 

Right now, I don't have access to the Win machine. However, the issue looks trivial, could you please fix it on your environment and submit a PR?

**Comment by Enmk** [comment]
@gcnote kind ping

**Comment by Enmk** [comment]
there seems to be no interest in that, closing

**Comment by gcnote** [comment]
您好，您发的邮件我已收到，谢谢！！！

**Comment by HRex39** [comment]
Try to fix that through Pull https://github.com/ClickHouse/clickhouse-cpp/pull/414
