### ISSUE TITLE
How to improve read speed

### ISSUE THREAD

**Issue by wangzhichao-github** [ClickHouse/clickhouse-cpp#235]
I'm using the client to read 50w rows and 70 columns of data, it takes 7 seconds to test down, I printed the relevant information and it shows a lot of 8196, it seems that the block limits the reading speed, is there any way to solve this? When I use the native client, it only takes 2.5s, but the native client does not support multi-threading.

**Comment by wangzhichao-github** [comment]
> 
Thank you for your reply @Enmk 
First, I am using centos 7.9 and the version of clickhouse is v22.9.3.18
Secondly, the example I used is the one in your readme, with some minor modifications after reading the data

   client.Select("SELECT id, name FROM default.numbers", [] (const Block& block)
        {
**I print block.GetRowCount() on this side, then there are many 8096, we sum many 8096 and the result is exactly 500000 (the number of rows of data I queried), so we wonder if we are requesting only 8096 rows in one request**
        }
    );


Third, the client I'm talking about is the official website of this
https://clickhouse.com/docs/en/integrations/sql-clients/clickhouse-client-local, it is very fast, 500000 rows and 70 columns of data takes only 2.5 seconds to read into memory

Translated with www.DeepL.com/Translator (free version)

**Comment by Enmk** [comment]
Well, it is hard to tell at this point what do you mean exactly without head-to-head comparison.
Could you please submit full example?

Btw, `block.GetRowCount()` describes how many rows were received from server in one block, client doesn't choose that.

**Comment by Enmk** [comment]
@wangzhichao-github ping

**Comment by Enmk** [comment]
Closing as stale, feel free to reopen if you have more info
