### ISSUE TITLE
Is there a plan to support secure connections like ClickHouse-client?

### ISSUE THREAD

**Issue by tdingus** [ClickHouse/clickhouse-cpp#24]
Hi,

ClickHouse server/client support secure connections via openssl. I wonder if there is a plan to support openssl in this client library. 

Thanks!

**Comment by prasadz** [comment]
I also wonder the same. What is plan to support secure connections? If this is not planned immediately can you please provide some suggestions?

**Comment by Enmk** [comment]
Fixed since 2.0
