### ISSUE TITLE
The client tcp socket  is leaked！

### ISSUE THREAD

**Issue by legendwind** [ClickHouse/clickhouse-cpp#241]
As we know,when a newclickhouse::Client class instance created, it will create a tcp socket and use the socket to communicate with the CK server. If the CK server is down before creating the new Client instance, the socket is leaked after a connection exception throwed!

**Comment by Enmk** [comment]
Hi @legendwind ! Thank you for reporting an issue, a similar one was reported some time ago: #208.

Could you please check against the master, since it was already fixed (and not yet releases) in #228
