### ISSUE TITLE
CMake: Linking clickhouse-cpp-lib target will not set the include directories correctly.

### ISSUE THREAD

**Issue by KuribohG** [ClickHouse/clickhouse-cpp#244]
I used `add_subdirectory(third_party/clickhouse-cpp EXCLUDE_FROM_ALL)` to import the targets of clickhouse library.

However in the root `CMakeLists.txt` of this project, the directories required is specified by `INCLUDE_DIRECTORIES`, not `TARGET_INCLUDE_DIRECTORIES`. So only linking the target in CMake is not enough, which is not encouraged by modern CMake practice.

Is it feasible to modify the CMake files, so external projects can import clickhouse more conveniently?

**Comment by Enmk** [comment]
Hi @KuribohG ! Thank you for reporting, sure, please submit a PR!
