### ISSUE TITLE
Bug ? Confused about type ColumnArrayT<ColumnArrayT<ColumnArrayT<ColumnString>>>

### ISSUE THREAD

**Issue by 1261385937** [ClickHouse/clickhouse-cpp#252]
```c++
std::vector<std::vector<std::vector<std::string>>> e = {
        {},
        {{"44"},{"55"},{}},
        {{"77"},{},{"99"}},
    };
```
The result1 is:
<img width="284" alt="1669215202831" src="https://user-images.githubusercontent.com/19810905/203577310-a565859c-84bb-472e-9f7d-22dd5d419c9c.png">

Or the result2 is:
<img width="295" alt="1669215260255" src="https://user-images.githubusercontent.com/19810905/203577565-5669bbaf-697c-4248-b926-0e98ff1f62ce.png">

I am very confused now.  I think result2  is more conventional. But now  nested ColumnArrayT is result1.
@Enmk

**Comment by 1261385937** [comment]
Execute  this  sql, but it is error.
```sql
SELECT [ [], [['11','22']] ] v, toTypeName(v);
```
![1669255859207](https://user-images.githubusercontent.com/19810905/203678607-8393b458-5e7c-4e9d-84a8-d14cc8142041.png)

Execute  this  sql, it is ok now,
```sql
SELECT [ [[]], [['11','22']] ] v, toTypeName(v);
```
![1669256025757](https://user-images.githubusercontent.com/19810905/203678915-e39d7cd6-b861-421e-933b-4cf1c5384d47.png)


So ColumnArrayT has bug?

**Comment by Enmk** [comment]
Hi @1261385937, Could you please post the whole example? Right now, I'm not sure that I understand the problem.

**Comment by 1261385937** [comment]
```c++
template<typename T, typename U = void>
struct is_ColumnArrayT
    :std::false_type
{
};
template<typename T>
struct is_ColumnArrayT<T, std::void_t<typename T::NestedColumnType>>
    :std::true_type
{
};
template<typename T>
constexpr bool is_ColumnArrayT_v = is_ColumnArrayT<std::decay_t<T>>::value;

template <typename Data>
    inline std::enable_if_t<is_ColumnArrayT_v<std::decay_t<Data>> &&
        !is_ColumnArrayT_v<typename std::decay_t<Data>::NestedColumnType>> AppendEmpty(Data&& nested_data) {
        nested_data.AddOffset(0);
    }

template <typename Data>
    inline std::enable_if_t< is_ColumnArrayT_v<std::decay_t<Data>> &&
        is_ColumnArrayT_v<typename std::decay_t<Data>::NestedColumnType>> AppendEmpty(Data&& nested_data) {
        nested_data.AddOffset(1);
        auto& nd = *typed_nested_data_;
        nd.AppendEmpty(nd);
    }

template <typename Container>
    inline void Append(const Container& container) {
        if (container.empty()) {
            return AppendEmpty(*this);
        }
        Append(std::begin(container), std::end(container));
    }

template <typename ValueType>
    inline void Append(const std::initializer_list<ValueType>& container) {
        Append(std::begin(container), std::end(container));
    }
```
upper code  make  the result2:
![image](https://user-images.githubusercontent.com/19810905/203748733-fac68502-7e74-4dd2-b4c3-136d3f3835d1.png)

So  empty  Array(Array(Array(String))) should like [[]]  or [[[]]] ?
I am not sure, but DBeaver use [[[]]] 
@Enmk

**Comment by Enmk** [comment]
@1261385937 I am still not sure what do you mean exactly.

Take a look at the test unit that we have: https://github.com/ClickHouse/clickhouse-cpp/blob/v2.3.0/ut/client_ut.cpp#L992
here test creates a 1-row column with a 3d array as an item.
So basically, if you print out column row-by-row, you'll get something like that:
```
Column: Array(Array(Array(UInt64))), 1 rows
row 0:       [[[1, 2, 3], [3, 2, 1]], [[4, 5, 6], [6, 5, 4]], [[7, 8, 9, 10], []], [[], [10, 9, 8, 7]]]
```

If you can modify that example a bit to have a 4-row 2D array:
```c++
    using ColumnType = ColumnArrayT<ColumnArrayT<ColumnUInt64>>;
    const std::vector<std::vector<std::vector<uint64_t>>> row_values = {
        {{1, 2, 3}, {3, 2, 1}},
        {{4, 5, 6}, {6, 5, 4}},
        {{7, 8, 9, 10}, {}},
        {{}, {10, 9, 8, 7}}
    };

    auto array = std::make_shared<ColumnType>();
    for (const auto & row : row_values)
        array->Append(row);
```
That gives something like that:
```
Column: Array(Array(UInt64)), 4 rows
row 0:       [[1, 2, 3], [3, 2, 1]]
row 1:       [[4, 5, 6], [6, 5, 4]]
row 2:       [[7, 8, 9, 10], []]
row 3:       [[], [10, 9, 8, 7]]
```
Note that I use same vectors to initialize both (2d and 3d) arrays, but do it somewhat differently.

And in both cases arrays have similar underlying data column with the same values at the same places, but shape (or number of nested levels) of the array is different.

**Comment by 1261385937** [comment]
First, thanks for you patience, @Enmk 👍 

1. This simple code has no probelm.
```c++
const std::vector<std::vector<std::vector<uint64_t>>> row_values = {
        {{1, 2}, {3, 2}},
        {{}, {10, 9}}
};

Column: Array(Array(Array(UInt64))), 1 rows
[[[1, 2], [3, 2]], [[], [10, 9]]]
```

2. Now I change row_values like this, yes, it is empty
```c++
const std::vector<std::vector<std::vector<uint64_t>>> row_values = {};

Column: Array(Array(Array(UInt64))), 1 rows
[]

But what I want is 
Column: Array(Array(Array(UInt64))), 1 rows
[[[]]]
```
For java spring boot ,this code is wrong
long array[][][] = data.getArrary()

This is my confuse

**Comment by 1261385937** [comment]
This may be jdbc bug :

**Comment by Enmk** [comment]
Do I get it right, that you rely on string representation of column/block generated with [`PrettyPrintBlock`](https://github.com/ClickHouse/clickhouse-cpp/blob/master/ut/utils.h#L95) ? This is just a debug helper, it might (and definitely has) some problems in some corner cases. And it is not part of official API, just a minor helper thing in unit-tests.

The sole goal of this library is to deliver data to/fetch data from ClickHouse server and not mess up in a process. So if you were able to store your arrays properly and read back the same data (with `clickhouse-cpp` and/or read/write values with `clickhouse-client`) -- there is no issue.

Having human-friendly string representation wasn't ever a goal. Comparing string representations of columns with other tools/libraries makes no sense in this light.

**Comment by Enmk** [comment]
Btw, 
```sql
:) select defaultValueOfTypeName('Array(Array(Array(UInt64)))')

┌─defaultValueOfTypeName('Array(Array(Array(UInt64)))')─┐
│ []                                                    │
└───────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.002 sec.
```

@1261385937 ^^

**Comment by 1261385937** [comment]
> Btw,
> 
> ```sql
> :) select defaultValueOfTypeName('Array(Array(Array(UInt64)))')
> 
> ┌─defaultValueOfTypeName('Array(Array(Array(UInt64)))')─┐
> │ []                                                    │
> └───────────────────────────────────────────────────────┘
> 
> 1 rows in set. Elapsed: 0.002 sec.
> ```
> 
> @1261385937 ^^

~~, picture speak thousands words !
