### ISSUE TITLE
Bug in EnumType::GetName

### ISSUE THREAD

**Issue by yb303** [ClickHouse/clickhouse-cpp#26]
An EnumType with empty map cores, or loops forever, depending on the implementation of std::map iterator.
It starts of with `it = map.begin()` and then increments `it` before checking for map.`== end()`

**Comment by Enmk** [comment]
Hi @yb303 ! Could you please provide a minimal viable example?

**Comment by yb303** [comment]
I don't have an example but the code is easy to read.
In line 182, a map iterator is used while it could `==end()` and in line 186 it's incremented so could get past `end()`.
I'm not saying an empty map is a valid case, but I believe there's no reason to core.
```
171 std::string EnumType::GetName() const {
172     std::string result;
173
174     if (GetCode() == Enum8) {
175         result = "Enum8(";
176     } else {
177         result = "Enum16(";
178     }
179
180     for (auto ei = value_to_name_.begin();;) {
181         result += "'";
182         result += ei->second;
183         result += "' = ";
184         result += std::to_string(ei->first);
185
186         if (++ei != value_to_name_.end()) {
187             result += ", ";
188         } else {
189             break;
190         }
191     }
192
193     result += ")";
194
195     return result;
196 }
```

**Comment by filimonov** [comment]
https://github.com/artpaul/clickhouse-cpp/commit/8cf843882fbb3005bd57ffecb5fac6106a7c96d9 ?
