### ISSUE TITLE
All the __int128 code is not building on windows

### ISSUE THREAD

**Issue by yb303** [ClickHouse/clickhouse-cpp#27]

**Comment by nshishov** [comment]
It's not possible to build library using Visual Studio

**Comment by victor-zou** [comment]
> It's not possible to build library using Visual Studio

Can it work with mingw?

I build it sucess with mingw (win7, gcc 10, latest version from winlibs), but the test program crushes directly (I modified the ip to the server ip, and add some cout in the beginning of the main and construct of NetrworkInitializer::NetrworkInitializerImpl). Not any print, crush direcly.

**Comment by Enmk** [comment]
Closed with #130
