### ISSUE TITLE
Crash when doing select query

### ISSUE THREAD

**Issue by DanielKui** [ClickHouse/clickhouse-cpp#271]
`clickhouse::ClientOptions opt;
	opt.SetHost("192.168.16.93");
	opt.SetPort(9000);
	opt.SetDefaultDatabase("stock_data");
	opt.SetUser("default");
	opt.SetPassword("dhhx");
	clickhouse::Client _clientck(opt);

	Logi("ck select begin");
	
	_clientck.Select("SELECT * FROM marketdata2 where sec_code='159949'", [](const clickhouse::Block& block)
	{
		Logi("ck select end,block.GetRowCount():{}", block.GetRowCount());

	}
	);`

my code as above, I got crash:
![image](https://user-images.githubusercontent.com/578118/208795879-d0466dc4-e7d1-4328-af1d-378feb95776b.png)

"SELECT * FROM marketdata2 where sec_code='159949'" result should have 646 records.
![image](https://user-images.githubusercontent.com/578118/208795941-f9f3bd41-9ca3-410c-9781-4cc7a9594c48.png)

If the select query result has 1 or 2 records, then that's OK, no crash.

Thank you very much for helps
my clickhouse-cpp version is 2.3.0
Connected to ClickHouse server version 18.16.1 revision 54412

**Comment by DanielKui** [comment]
Hi, anybody help me?

**Comment by Enmk** [comment]
Hi @DanielKui thank you for reporting the issue. Could you please provide a minimal example that reproduces the crash?

That would be: The table structure (`CREATE TABLE` statement) and data (`INSERT` statement). I believe there are some columns you are trying to read from CH is not supported by clickhouse-cpp.

Also, is it really a crash or exception thrown from inside the library? In case of exception, please provide full error message.

**Comment by DanielKui** [comment]
[main.zip](https://github.com/ClickHouse/clickhouse-cpp/files/10312357/main.zip)
Attached is my example code ,but the whole running time may takes a long time for inserting 1000000 rows,

**Comment by Enmk** [comment]
> I can not get the whole rows in separated SelectCallback?

**Comment by DanielKui** [comment]
> 

Thanks for your response.
I totally receive these 2 callback 0 and 8192. no others

**Comment by DanielKui** [comment]
Hi, any updates?

**Comment by 1261385937** [comment]
Your example code can not work well

**Comment by 1261385937** [comment]
Hi, @DanielKui 
Firstly, 18.16.1 is too old now, we can not get the env.
Secondly, there is no guarantee that the stock data is free of duplicates with ReplacingMergeTree if you use in production environment.
Thirdly,  with ReplacingMergeTree, can not always  get the same count about your example code.
At last, I replace ReplacingMergeTree with MergeTree, and everything is ok.

So  we need another minimal crash example about recent version.

**Comment by DanielKui** [comment]
> Hi, @DanielKui Firstly, 18.16.1 is too old now, we can not get the env. Secondly, there is no guarantee that the stock data is free of duplicates with ReplacingMergeTree if you use in production environment. Thirdly, with ReplacingMergeTree, can not always get the same count about your example code. At last, I replace ReplacingMergeTree with MergeTree, and everything is ok.
> 
> So we need another minimal crash example about recent version.
> 
> My env is 22.8.9.24

Thanks for you help, close this issue.
