### ISSUE TITLE
Is there a way of converting Column ->std::vector?

### ISSUE THREAD

**Issue by homedry** [ClickHouse/clickhouse-cpp#275]
I see only slicing and indexing in class Column. It would be convenient to be able to convert a Column object to a std::vector object.

Is there the method?

**Comment by Enmk** [comment]
Hi! What kind of column are you using? For ColumnVector there is vector-like interface with `operator[]`, etc.

Basically there is no cheap (`O(1)` CPU and no memory copies) way of converting data from column to `std::vector`.
But you can always copy values into vector one-by-one if you wish...

**Comment by homedry** [comment]
> Hi! What kind of column are you using? For ColumnVector there is vector-like interface with `operator[]`, etc.
> 
> Basically there is no cheap (`O(1)` CPU and no memory copies) way of converting data from column to `std::vector`. But you can always copy values into vector one-by-one if you wish...

I thought DataFrame library(https://github.com/hosseinmoein/DataFrame) goes well with Clickhouse. And It requires columns as vectors when constructing DataFrame object.

But it's OK without it, if I depend on querying more, post-processing with DataFrame is not necessary. 

Thank you for the reply!
