### ISSUE TITLE
Strange behavior `As` function with column type Array(Float32)

### ISSUE THREAD

**Issue by alexeycas6** [ClickHouse/clickhouse-cpp#280]
I have a table with the following structure
![Снимок экрана 2023-01-23 110209](https://user-images.githubusercontent.com/10243466/213975085-0aa20e11-f8db-46c9-b9e5-37a4f9580ab2.png)

data is presented here:
![image](https://user-images.githubusercontent.com/10243466/213975201-934d650a-ca52-4853-8caa-1b0764902f3f.png)
500 rows with 1500 elements in each array.

exception `column index is out of range` is thrown after request is executed
``` C++
 client.Select("SELECT trace FROM cube1.traces", [](const clickhouse::Block& block)
        {
            auto row_count = block.GetRowCount();
            auto column_count = block.GetColumnCount();
            auto test = block[0]->As<clickhouse::ColumnArray>();          
        }
    );
```
Why?
It is not clear why the request block enters the block 2 times. For the first time `row_count = 0 ` and `column_count = 1`. Second  `row_count = 500 ` and `column_count = 1`. After that exception is thrown.

**Comment by 1261385937** [comment]
code should like this:
```cpp
for (size_t c = 0; c < block.GetRowCount(); ++c) {
...
}
```
>Enter the block 2 times

 Just handle the server response, has no problem

**Comment by alexeycas6** [comment]
@1261385937 Thanks!
And one more question: how to get data located in column type Array(Float32)?
```C++
auto test = block[0]->As<clickhouse::ColumnArray>();
```
How to cast test to std::vector?

**Comment by 1261385937** [comment]
Not yet, a pr is welcome.

**Comment by alexeycas6** [comment]
Hi @Enmk ! Thank you for answer. Found the necessary information in tests.
```C++
auto test = block[0]->As<clickhouse::ColumnArray>()->GetAsColumn(0)
                    ->As<clickhouse::ColumnFloat32>();
```

**Comment by Enmk** [comment]
@alexeycas6 Please note that `block[0]->As<clickhouse::ColumnArray>()->GetAsColumn(0)->As<clickhouse::ColumnFloat32>();` would make a copy of your data... I recommend doing `clickhouse::ColumnArrayT<clickhouse::ColumnFloat32>::Wrap(block[0]->As<clickhouse::ColumnArray>())` instead
