### ISSUE TITLE
Insert lots data but cannot query them in table

### ISSUE THREAD

**Issue by SnowfallDan** [ClickHouse/clickhouse-cpp#282]
I have 7000 datas need insert into a table.
I use a threadpool to do the inserts. Each thread has its own CK client.
 

code: 
`void send(Data field)
{
    auto marketIndicator = std::make_shared<clickhouse::ColumnString>();
    auto direction = std::make_shared<clickhouse::ColumnString>();
    auto execType = std::make_shared<clickhouse::ColumnString>();
    auto bondID = std::make_shared<clickhouse::ColumnString>();
    auto exchangeID = std::make_shared<clickhouse::ColumnString>();
    auto execID = std::make_shared<clickhouse::ColumnString>();
    auto ytm = std::make_shared<clickhouse::ColumnFloat64>();
    auto amount = std::make_shared<clickhouse::ColumnFloat64>();
    auto price = std::make_shared<clickhouse::ColumnFloat64>();
    auto tradeDate = std::make_shared<clickhouse::ColumnString>();
    auto tradeTime = std::make_shared<clickhouse::ColumnString>();
    marketIndicator->Append("xxx");
    bondID->Append(field.BondID);
    exchangeID->Append(field.ExchangeID);
    // each data is different
    execID->Append(field.ExecID);
    ytm->Append(field.YTM);
    amount->Append(field.Amount);
    price->Append(field.Price);
    tradeDate->Append("20230210");
    tradeTime->Append(field.TradeTime);
    Block marketDataBlock;
    marketDataBlock.AppendColumn("marketIndicator", marketIndicator);
    marketDataBlock.AppendColumn("direction", direction);
    marketDataBlock.AppendColumn("execType", execType);
    marketDataBlock.AppendColumn("bondID", bondID);
    marketDataBlock.AppendColumn("exchangeID", exchangeID);
    marketDataBlock.AppendColumn("execID", execID);
    marketDataBlock.AppendColumn("ytm", ytm);
    marketDataBlock.AppendColumn("amount", amount);
    marketDataBlock.AppendColumn("price", price);
    marketDataBlock.AppendColumn("tradeDate", tradeDate);
    marketDataBlock.AppendColumn("tradeTime", tradeTime);

    // boost io_service pool
    getClickHouseClientPool()->PostWork([marketDataBlock](ClickHouseClientPtr& client)
                                        {
                                            if (client == nullptr)
                                            {
                                                LOG_ERROR("FATAL!");
                                                return;
                                            }

                                            boost::posix_time::ptime t(boost::posix_time::second_clock::local_time());
                                            string tableName = "xxxxx";

                                            bool writeOK = false;
                                            try
                                            {
                                                client->getClient().Insert(tableName, marketDataBlock);
                                                LOG_DEBUG("Insert OK！ table = {}, count = {}", tableName, m_count);
                                                writeOK = true;
                                            }
                                            catch (std::exception &e)
                                            {
                                                LOG_ERROR("Insert Error, table = {}， message = {}", tableName,
                                                          e.what());
                                            }
                                        });
}
void start()
{
    std::vector<Data> dataVec;
    for(int i = 0; i < 7000; i++)
        send(dataVec[i]);
}`

Table DDL:
`
-- auto-generated definition
create table xxxxx
(
    marketIndicator String ,
    direction       String,
    execType        String,
    bondID          String,
    bondName        String,
    exchangeID      String',
    execID          String,
    ytm             Float64,
    amount          Float64,
    price           Float64',
    dirtyPrice      Float64,
    tradeDate       String,
    tradeTime       String,
    receiveTime     String
)
    engine = ReplacingMergeTree PARTITION BY toYYYYMM(toDate(tradeDate))
        ORDER BY (tradeDate, bondID, execID)
        SETTINGS index_granularity = 8192;
`

Every Insert Operation is successful. But I only can query 100+ results .

`select count(*) from IBSP_XBOND_DEAL where tradeDate = '20230210' -- 184 rows;`

clickhouse server log find none error.....
anyone has any idea....

**Comment by bigKoki** [comment]
Hello, I run into this problem too. I use multi-thread to write data into clickhouse, and I can only query little results, could you please tell what cause this and how to resolve it?
