### ISSUE TITLE
Select hangs on a server version 18.16.1

### ISSUE THREAD

**Issue by cpubug** [ClickHouse/clickhouse-cpp#304]
With the libraries version 2.3.0 and 2.4.0 **Select** gets all the data but doesn't finish. The library version 2.2.1 works fine.

**Comment by Enmk** [comment]
Hi @cpubug Could you please provide a minimal reproducible example?

**Comment by cpubug** [comment]
Hi @Enmk the example from README.md can be used to reproduce this issue.

**Comment by Enmk** [comment]
Well, 18.6 is very old... could you please concinder switching to at least `22.3`? `21.3` should also work, but unfortunatelly we don't check it in CI/CD
![image](https://github.com/ClickHouse/clickhouse-cpp/assets/1110183/c967dec1-5884-4eef-992e-9e957b1814c7)

Also, it would be great if you'd be able to update [our workflows](https://github.com/ClickHouse/clickhouse-cpp/blob/master/.github/workflows/linux.yml) to use 21.3 just to make sure that it is properly supported.
