### ISSUE TITLE
TRUNCATE TABLE Operation timed out

### ISSUE THREAD

**Issue by giosh04** [ClickHouse/clickhouse-cpp#306]
Hello!
When i do loop with two queries

client->Execute("INSERT INTO FUNCTION remote('"+remote_db_host+"',"+remote_db_name+","+table+",'"+remote_db_user+"','"+remote_db_pass+"',rand()) SELECT * from "+db_name+"."+table);
client->Execute("TRUNCATE TABLE " + table);

On second loop I get
"closed: Operation timed out"

Can you please help me to solve it?

**Comment by Enmk** [comment]
Hi @giosh04 could you please share what was the problem and how did you solved it?
