### ISSUE TITLE
Dereferencing of the null pointer 'block'

### ISSUE THREAD

**Issue by pavel-pimenov** [ClickHouse/clickhouse-cpp#307]
V522 [CWE-476] Dereferencing of the null pointer 'block' might take place. string.cpp 267

https://github.com/ClickHouse/clickhouse-cpp/blob/85dae8e9d971d997242735498d124a11f538d8fe/clickhouse/columns/string.cpp#L267

**Comment by Enmk** [comment]
That is a false positive, `block` can be `nullptr` only if `blocks_.size() == 0`.
