### ISSUE TITLE
Broken Pipe or insertions fail silently - how to set timeouts?

### ISSUE THREAD

**Issue by pkoosha** [ClickHouse/clickhouse-cpp#313]
I have a program that is inserting into clickhouse server using clickhouse cpp.
I get broken pipe in the middle of insertions or if the insertion takes longer that <keep_alive_timeout>3</keep_alive_timeout> parameter in config.xml, it closes the connection.

I was wondering how can I set the read and write timeouts when I am establishing connections to clickhouse-server from this library?

Thanks

**Comment by 1261385937** [comment]
```cpp
clickhouse::ClientOptions()
		.SetHost(ip)
		.SetPort(port)
		.SetUser(user)
		.SetPassword(passwd)
		.SetPingBeforeQuery(true)
		.SetConnectionRecvTimeout(std::chrono::seconds(5))
		.SetConnectionSendTimeout(std::chrono::seconds(5)
```
