### ISSUE TITLE
class clickhouse::ColumnArrayT<clickhouse::columnIpv4> has no member named begin.

### ISSUE THREAD

**Issue by vovchick12385** [ClickHouse/clickhouse-cpp#324]
class clickhouse::ColumnArrayT<clickhouse::columnIpv4> has no member named begin.
Hello. I'm trying to iterate over such a container, but the compiler throws errors. I found the begin and end methods in the code and they seem to be public. Why can't I access these methods?

**Comment by vovchick12385** [comment]
![image](https://github.com/ClickHouse/clickhouse-cpp/assets/69983607/f3ecce09-320d-45e7-a5ea-219089f0af92)

**Comment by mishamarkov15** [comment]
@vovchick12385 Hello! Can you help please? How did you solved this?
