### ISSUE TITLE
CRC failed

### ISSUE THREAD

**Issue by mmitkevich** [ClickHouse/clickhouse-cpp#325]
with latest clickhouse-client-cpp release  and clickhouse-server 23.x I get CRC error when using LZ4 compression in client.

I digged into CRC and server's ipml
https://github.com/ClickHouse/ClickHouse/blob/17f37541935bce25e2b200f061baafa4dadb338e/contrib/cityhash102/src/city.cc#L344
<img width="674" alt="image" src="https://github.com/ClickHouse/clickhouse-cpp/assets/3052367/c11ed939-fb6b-44c3-8dc8-12c094ebbee4">

looks just like client's impl 

https://github.com/ClickHouse/clickhouse-cpp/blob/master/contrib/cityhash/cityhash/city.cc#L339
<img width="712" alt="image" src="https://github.com/ClickHouse/clickhouse-cpp/assets/3052367/88fb953e-d7d1-4044-b5b1-c15077d8189f">

but it does not work anymore. Probably it's worth to use the server's code here?

here is my server problem desc
https://github.com/ClickHouse/ClickHouse/issues/53932

**Comment by Enmk** [comment]
Hi @mmitkevich thank you for reporting! Yes, we might sure want to be compatible with ClickHouse's server implementation.

Could you please create a PR with proposed changes?

**Comment by Enmk** [comment]
Hi @mmitkevich could you please provide more info on that? I tested against 23.8 and wasn't able to reproduce the issue.

Do you have any sample code that reproduces that?

**Comment by Enmk** [comment]
Hi, @mmitkevich! Have you by any chance used cityhash 1.1 which comes as an OS package? IIRC some versions might be incompatible...
