### ISSUE TITLE
how to read  a column of  LowCardinality(Nullable(string))

### ISSUE THREAD

**Issue by changvin** [ClickHouse/clickhouse-cpp#326]
version: 2.4.0 
gcc version:  8.3.1 
system:  centos 7,  linux version 3.10.0-957.el7.x86 64

Hi, I'm new to clickhouse so I'm testing it.
but I  facing a type cast problem.
this my code :
![1694159148859](https://github.com/ClickHouse/clickhouse-cpp/assets/42169579/7d058d8d-e5df-4d88-8d84-3fbb87df2a98)

but it seem no right, print std::bad_cast
![1694158862679](https://github.com/ClickHouse/clickhouse-cpp/assets/42169579/43dcd05a-6dbf-49b2-9f6e-933439f05e41)

```[tasklist]
### Tasks
```

**Comment by Enmk** [comment]
Hi @changvin ! Thanks to @den818 you can do the following:

```c++
auto col = column->As<ColumnLowCardinalityT<ColumnNullableT<ColumnString>>>();
```

Then `col->At(0)` is going to return `std::optional<std::string>`.

There is a test case for it (might be a bit convoluted) right here: https://github.com/ClickHouse/clickhouse-cpp/blob/4f929e985997f490304c692df51dfab06bd38c1a/ut/roundtrip_tests.cpp#L213

**Comment by Enmk** [comment]
Btw, next time, please attach the code as text, not as a picture... it is much easier to play around and/or modify it like that.

**Comment by changvin** [comment]
> Hi @changvin ! Thanks to @den818 you can do the following:
> 
> ```c++
> auto col = column->As<ColumnLowCardinalityT<ColumnNullableT<ColumnString>>>();
> ```
> 
> Then `col->At(0)` is going to return `std::optional<std::string>`.
> 
> There is a test case for it (might be a bit convoluted) right here:
> 
> https://github.com/ClickHouse/clickhouse-cpp/blob/4f929e985997f490304c692df51dfab06bd38c1a/ut/roundtrip_tests.cpp#L213

this is a  insert LowCardinalityTNullableString column  test case  not  read ,

**Comment by Enmk** [comment]
Please check master now, most likely you've had `ClientOptions::backward_compatibility_lowcardinality_as_wrapped_column` set to `true` and that's why the `LowCardinality(String)` column was unwrapped into just `String`.

**Comment by changvin** [comment]
> 请现在检查大师，很可能您已经`ClientOptions::backward_compatibility_lowcardinality_as_wrapped_column`设置为`true`，这就是该`LowCardinality(String)`列已展开为`String`。

@Enmk 
Thank you for your reply，
I'm pretty sure `ClientOptions::backward_compatibility_lowcardinality_as_wrapped_column` set  to false before，maybe `ColumnLowCardinalityT` not work  with `ColumnNullableT` when read ?

**Comment by Enmk** [comment]
> > 请现在检查大师，很可能您已经`ClientOptions::backward_compatibility_lowcardinality_as_wrapped_column`设置为`true`，这就是该`LowCardinality(String)`列已展开为`String`。
> 
> @Enmk Thank you for your reply， I'm pretty sure `ClientOptions::backward_compatibility_lowcardinality_as_wrapped_column` set to false before，maybe `ColumnLowCardinalityT` not work with `ColumnNullableT` when read ?

Please see https://github.com/ClickHouse/clickhouse-cpp/pull/339

[This one confirms that it works](https://github.com/ClickHouse/clickhouse-cpp/pull/339/files#diff-5ba05c8bd7182b90fb7e5b5b010e00c29c723612eb084a0b24b6f897fb45c531L215)
