### ISSUE TITLE
feature request: version define in headers

### ISSUE THREAD

**Issue by itrofimow** [ClickHouse/clickhouse-cpp#347]
Hi!

Would it be possible to add some version defines into, say, client.h?

----

Context: i'm in the process of upgrading clickhouse-cpp from 2.4.0 to 2.5.1 in https://github.com/userver-framework/userver, and there is a breaking change in `SocketFactory`: https://github.com/ClickHouse/clickhouse-cpp/commit/87804a0bd02e58dabe030f2c19d02592771af58c#diff-e9fca18abd02a909ee38e214ec9ed247dbbf0491e411409c5d4943071b19c70aR92

I have to support a range of different clickhouse-cpp versions, and right now i have to dance around this change like this
```
// Clickhouse-cpp broke the API in 2.5.0:
// now connect takes an additional parameter 'const Endpoint&'.
//
// We don't need that anyway, but have to somehow override the function,
// so we maintain two versions which both resolve to the same logic.
class ClickhouseCppSocketFactoryHack : public clickhouse_cpp::SocketFactory {
 public:
  // NOLINTNEXTLINE
  std::unique_ptr<clickhouse_cpp::SocketBase> connect(
      const clickhouse_cpp::ClientOptions& opts,
      // This Endpoint value comes from 'endpoints' field in opts, which we
      // don't use, since we only have one host/port pair per connection
      const clickhouse_cpp::Endpoint&) {
    return DoConnect(opts);
  }

  // NOLINTNEXTLINE
  std::unique_ptr<clickhouse_cpp::SocketBase> connect(
      const clickhouse_cpp::ClientOptions& opts) {
    return DoConnect(opts);
  }

 protected:
  virtual std::unique_ptr<clickhouse_cpp::SocketBase> DoConnect(
      const clickhouse_cpp::ClientOptions& opts) = 0;
};
```
which is a bit ugly in my opinion, requires clang-tidy suppression etc.

What i would like to do instead is to add `const clickhouse_cpp::Endpoint&` parameter conditionally under version `ifdef`, but right now there isn't anything for the `ifdef` to depend on.

**Comment by Enmk** [comment]
Sure, how would you like that macro to look like? 
Does `CLICKHOUSE_CPP_VERSION` look good? With value like `020501` for `v2.5.1`

**Comment by itrofimow** [comment]
Sounds nice to me!

**Comment by Enmk** [comment]
Hi @itrofimow! I've recently merged  `CLICKHOUSE_CPP_VERSION` into master, what versions of clickhouse-cpp do you need to support?

I was thinking about creating new patch versions of those with changes from #348, so you'd be able to differentiate between versions in your code.

**Comment by itrofimow** [comment]
Excellent, thank you @Enmk !

Right now i support 2.4.0 -> 2.5.1 (and maybe some older versions work too), and with this addition in place it'll be much easier for me to adjust to not-so-much-breaking changes going forward, without a need to bother you.

So thank you once again, much appreciated.
