### ISSUE TITLE
closed: No such file or directory

### ISSUE THREAD

**Issue by druidfund** [ClickHouse/clickhouse-cpp#349]
I use Insert function to insert data to clickhouse in an event driving application,  it is works fine for event is continues coming, but after a few minutes of no event comming and resume data processing, client throw exception like: 
`closed: No such file or directory`
after that more exception throw out :
`fail to send 432 bytes of data: Broken pipe`
is there any suggest to solve this issue?

**Comment by Enmk** [comment]
Hi @druidfund ! Thanks for reporting an issue, could you please provide some details?
- Version of the library
- platform for which it was built
- ClickHouse server version

Maybe a minimal code sample that reproduces the problem?
That would help to identify and fix the problem.
