### ISSUE TITLE
zSTD Support

### ISSUE THREAD

**Issue by cliffburdick** [ClickHouse/clickhouse-cpp#35]
Hi, is there a reason zstd support isn't in this client? Would you be willing to accept a PR for it or is there a reason it's purposely left out?

**Comment by Enmk** [comment]
Generally, any PRs are welcome. But just to clarify, do you want to implement an additional client-server protocol compression method?

**Comment by alexey-milovidov** [comment]
@Enmk This compression method is already supported in ClickHouse, look at the
`network_compression_method`
`network_zstd_compression_level`
settings.

**Comment by cliffburdick** [comment]
> @Enmk This compression method is already supported in ClickHouse, look at the
> `network_compression_method`
> `network_zstd_compression_level`
> settings.

Yes, I should have clarified that it's already supported on the server, and the client is the only one lacking support.

**Comment by Enmk** [comment]
Great, you are very welcome to add ZSTD support on ClickHouse-cpp side. Also, please make sure to add some tests to the PR 🙏
