### ISSUE TITLE
Maybe add prefix for all defined cmake build options?

### ISSUE THREAD

**Issue by german3w1** [ClickHouse/clickhouse-cpp#358]
Hi, @Enmk!. 
I noticed that all the build options in the root `CMakeLists.txt` do not have any prefixes to ensure that they do not overlap with other project options when included as a dependency.
How about sacrificing a little backwards compatibility and adding the prefix `CLICKHOUSE_CPP_` to the name of each option (in the `YAML_CPP` library its authors went exactly this way, for example)

Example for clickhouse: `BUILD_TESTS` ->  `CLICKHOUSE_CPP_BUILD_TESTS` 

I'll do this if you find the idea is worth

**Comment by Enmk** [comment]
Sure, let's do it! I think that this might be a good idea for a 3.0 release.

**Comment by Enmk** [comment]
Fixed in https://github.com/ClickHouse/clickhouse-cpp/pull/360
