### ISSUE TITLE
suggestion: set CHECK_VERSION to OFF by default

### ISSUE THREAD

**Issue by rr0gi** [ClickHouse/clickhouse-cpp#359]
CHECK_VERSION ON makes it a problem to use clickhouse-cpp as git subtree
thanks for providing option it is easy to turn it off but I would argue that it should be the default

**Comment by Enmk** [comment]
Ok, that perhaps makes sense...
Could you please share what kind of problems you see when using this project as a submodule?

**Comment by Gnayj** [comment]
Hi I have the same issue. It will pop this kind of error: 
CMake Error at src/contribs/clickhouse-cpp/cmake/version.cmake:69 (message):
  version obtained from `git describe` doesn't look like a valid version:
  "1.2.1-10-gd2820d9"
Call Stack (most recent call first):
  src/contribs/clickhouse-cpp/CMakeLists.txt:29 (clickhouse_cpp_check_library_version)
