### ISSUE TITLE
Add support for DateTime64 type.

### ISSUE THREAD

**Issue by tshev** [ClickHouse/clickhouse-cpp#36]
The type is supported by the DBMS https://clickhouse.tech/docs/en/sql_reference/data_types/datetime64/, but not by this client. This evening I did some initial work (it seemed like an easy task), but I don't know enough about the internals.

**Comment by Enmk** [comment]
Hi @tshev ! You are welcome to add DateTime64 implementation, on the server side it has same binary layout as Decimal64. 

So it should be rather simple since Decimals are already supported by this client.

**Comment by tshev** [comment]
Thank you. Here we go: https://github.com/ClickHouse/clickhouse-cpp/pull/38/files

**Comment by filimonov** [comment]
Fixed in https://github.com/ClickHouse/clickhouse-cpp/pull/50
