### ISSUE TITLE
#include <ut/utils.h> depends on gtest

### ISSUE THREAD

**Issue by socketpair** [ClickHouse/clickhouse-cpp#379]
This is a bug, headers for use in production should not depend on gtest.

**Comment by Enmk** [comment]
this is not a header intended for a production, only for developers of the library itself... in fact it shouldn't even be present on a client's machine. All binaries that are supposed to end up on client's machine after "installation" are [specified here](https://github.com/ClickHouse/clickhouse-cpp/blob/master/clickhouse/CMakeLists.txt#L155-L208)

**Comment by socketpair** [comment]
Anyway, I would like to use utils as a developer without gtest

**Comment by Enmk** [comment]
Well, then you can ☺️

But nevertheless, this is not a reason to bloat public API (and hence cost of support) of the library.
