### ISSUE TITLE
ProtocolError: Fail to connect to server

### ISSUE THREAD

**Issue by DKGH** [ClickHouse/clickhouse-cpp#388]
I am getting the error mentioned in the subject line while trying to connect to a clickhouse server using host, port, username, and password. How can I get more details about why this error happened?

**Comment by 1261385937** [comment]
please show you simple code @DKGH

**Comment by DKGH** [comment]
It is a modified version of tests/simple/main.cpp from the GitHub codebase:
```
int main() {
try {
  const auto localhost = ClientOptions().SetHost("hostname").SetPort(8080).SetUser("user").Set password("password");
Client client(localhost);
} catch (cont ProtocolError & e) {
  cout << e.what();
} catch (const std:: exception& e) {
  cout << e.what();
}
return 0;
}
  
```

**Comment by DKGH** [comment]
It seems that I was connecting to HTTP port instead of TCP port. I needed to forward more ports from my ClickHouse server container.
