### ISSUE TITLE
What is the official C++ client library for ClickHouse?

### ISSUE THREAD

**Issue by thekvs** [ClickHouse/clickhouse-cpp#5]
I noticed that documentation [here](https://clickhouse.yandex/docs/en/interfaces/third-party/client_libraries/) recommends using https://github.com/artpaul/clickhouse-cpp/ repository for C++ client library but on the other hand repository here seems to be under official github organization for ClickHouse. So which one should be used?

**Comment by alexey-milovidov** [comment]
We have forked clickhouse-cpp library for easy development inside our team in Yandex and Altinity.
This fork is going to be the officially recommended version.

There is no difference between these forks right now.

**Comment by blinkov** [comment]
@thekvs that part of documentation just needs some refactoring, we'll do it hopefully soon enough.
