### ISSUE TITLE
V522 Dereferencing of the null pointer 'block'

### ISSUE THREAD

**Issue by pavel-pimenov** [ClickHouse/clickhouse-cpp#62]
https://github.com/ClickHouse/clickhouse-cpp/blob/ad5fd98e261297837098f6e60d8b56e8dcb2811c/clickhouse/columns/string.cpp#L219
..
https://github.com/ClickHouse/clickhouse-cpp/blob/ad5fd98e261297837098f6e60d8b56e8dcb2811c/clickhouse/columns/string.cpp#L227

**Comment by Enmk** [comment]
`block` is `nullptr` only when `block_.size() == 0`, condition short-circuits and the second part is not evaluated.
