### ISSUE TITLE
Exception on inserting LowCardinality(Nullable(String)) 

### ISSUE THREAD

**Issue by andyongh** [ClickHouse/clickhouse-cpp#76]
Try to insert data to field LowCardinality(Nullable(String)), 
exception throw:
   LowCardinality(Nullable) not supported

Questions:
1) Does the clickhouse-cpp support LowCardinality(Nullable(String))
2) Any unit test or example on LowCardinality() type

Thanks a lot!

**Comment by arthurpassos** [comment]
Working on it

**Comment by UnamedRus** [comment]
BTW as workaround its possible to tell ClickHouse to convert LC(T) format to T via setting: `low_cardinality_allow_in_native_format=0`
