### ISSUE TITLE
Fixes for compile and work in Windows (with mingw)

### ISSUE THREAD

**Issue by victor-zou** [ClickHouse/clickhouse-cpp#80]
1. need add definition `_WIN32_WINNT` for your window version (at leat 0x0600, or will not have `WSAPoll`)
2. might need define `WIN32_LEAN_AND_MEAN` (not affected here, but might affect other places)
3. get `errno` in the Windows socket world should use `WSAGetLastError`
4. `connect` in non blocking mode will always return -1 and set errno `WSAEWOULDBLOCK`. I commented the `SetNonBlock` before the `connect`s.
5. a bug in gcc8 (at least fixed in gcc10), in the declaration of WSAPoll, a `const void *` signature missed `const`, neet add const_cast for fix

**Comment by filimonov** [comment]
Can you just send pull request?

**Comment by victor-zou** [comment]
> Can you just send pull request?

Sorry, I made those modifications in a local network. It is not very convenient for my to test it in the public internet. I have listed all the modifications I've made, in case that if any one want to use the client with mingw can, at least, do it himself. Of cause, it would be more than best for any volenteer to do the "pull request" thing.

**Comment by lordalexshen** [comment]
victor-zou
yes, it's works thanks a lot

**Comment by filimonov** [comment]
> > Can you just send pull request?
> 
> Sorry, I made those modifications in a local network. It is not very convenient for my to test it in the public internet. I have listed all the modifications I've made, in case that if any one want to use the client with mingw can, at least, do it himself. Of cause, it would be more than best for any volenteer to do the "pull request" thing.

You can just send patch file, it's as simple as `git diff > mypatch.patch`

**Comment by Enmk** [comment]
Closed with https://github.com/ClickHouse/clickhouse-cpp/pull/137
