### ISSUE TITLE
Using of clickhouse-cpp with C++11 codebase

### ISSUE THREAD

**Issue by agamanin** [ClickHouse/clickhouse-cpp#97]
Hi Clickhouse Team.

I'v been using some two-year-old snapshot of the clickhouse-cpp library for the last couple of years and it worked just fine with my C++11 codebase. However, now I need to use DateTime64 columns, that's why I'm trying to upgrade to the latest version. Ooops... Now it is strictly C++17, so I cannot use it from my C++11 codebase. Migrating the huge codebase to C++17 would be an immense task (although inevitable in the future). Moreover, C++11 is the only 'native' standard for my RHEL 7.5 (yes, it is awful).

What I'v tried:
1. Compile the clickhouse-cpp with RHEL's devtoolset-7 and then link the so to my code. No success (obviously) as the headers rely in C++17 features (such as string_view) - so my version of gcc cannot handle it.
2. Prepare a tiny wrapper of my code encapsulating all the communications with clickhouse-cpp, and build it as a static library with RHEL's devtoolset-7, then link this library + clickhouse-cpp so to my main executable. RHEL/gcc promise the ABI compatibility. Successfully linked, but crashes due to memory corruption during execution, somewhere in the CH connection establishment procedure.

There are other crazy options like reading with Python or native client in a dedicated process and then passing the results to C++ part, which I would like to avoid as much as possible.

Any advice would be appreciated with respect to possible ways to use clickhouse-cpp from C++11.

BR, Andrey.

**Comment by filimonov** [comment]
We have a branch for gcc-6  https://github.com/ClickHouse/clickhouse-cpp/tree/master-gcc-6
