### ISSUE TITLE
exception : fail to connect: Operation completed successfully

### ISSUE THREAD

**Issue by goutaiping** [ClickHouse/clickhouse-cpp#98]
Hi @Enmk:
             I'm happy to use clickhouse-cpp, and I successfully compiled the library under Qt Creator5.9.8 software, but when I run the test program I have a problem, and I need your help. It always reports an error: "exception : fail to connect: Operation completed successfully", Looking forward to your reply, Thank you very much!

**Comment by Enmk** [comment]
Hi @goutaiping, sorry for a late reply! Could you please share a code sample that reproduces the error?

**Comment by Enmk** [comment]
Closed due to inactivity
